storybook/.storybook/manager-head.html
Add Google Search Console verification tag. Once it's merged - I'll send you invite to be admin at https://search.google.com/search-console. It provides useful info and tools. We should add site to Bing Webmaster tools too.
=> Add Google Search Console verification tag

storybook/stories/introduction/welcome.stories.mdx
Requested by the Trimble Modus Delivery Team
Closes #343
=> Storybook: Update the Welcome page's intro text

.github/workflows/publish.yml, README.md, package.json
Update the `publish.yml` to publish to the npm registry using the new automation token (which is a PAT on my acc)
Fix hard coded version badge, and add contributor count badge to the `README.md`
References #357
=> Publish package to npm registry. Bump version to 0.1.0.

.github/dependabot.yml
Per discussion https://github.com/trimble-oss/modus-web-components/discussions/124#discussioncomment-2218349
Closes #376
=> Update Dependabot checks to occur monthly rather than weekly

src/components.d.ts, src/components/modus-navbar/modus-navbar.tsx, src/components/modus-navbar/readme.md, storybook/package-lock.json, storybook/package.json, storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, storybook/stories/introduction/welcome.stories.mdx
Add an option to change the Navbar's height, and update the Storybook dependency
References AB#382464
=> Add height option to the Navbar's product logo

package-lock.json, package.json, src/components/modus-navbar/modus-navbar.tsx
Use user initials if avatar image is broken
=> Use user initials if avatar image is broken

CHANGELOG.md, package-lock.json, package.json, src/components/modus-select/modus-select.scss
- Before: any elements in the dropdown list with too long of text ended up wrapping and taking up more space than their given container
- Now: any item in the list with text that is longer than the bounds of the dropdown container gets cutoff 
Closes #395
=> Styling fix for dropdown list elements wrapping if too long

CHANGELOG.md, package-lock.json, package.json, src/components.d.ts, src/components/modus-navbar/modus-navbar.e2e.ts, src/components/modus-navbar/modus-navbar.scss, src/components/modus-navbar/modus-navbar.tsx, src/components/modus-navbar/readme.md, storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
=> Add Shadow to NavBar

.github/pull_request_template.md, CHANGELOG.md, SUPPORT.md, package.json
Add `SUPPORT.md` with information on submitting a new Issue, and opening a Discussion.
`SUPPORT.md` is also included in the package for the consumer.
References #378
*Also updated the PR template to include a check for CHANGELOG updates (I forgot to update it on my last PR, so this seems like a good check 😉)
Packed and installed the NPM package. `SUPPORT.md` is included.
=> Add SUPPORT.md

CHANGELOG.md, package-lock.json, src/components.d.ts, src/components/modus-navbar/modus-navbar.tsx, src/components/modus-navbar/readme.md, storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Add exposed method to hide the navbar's main menu
Verified locally with a manual test
=> Add Navbar's hideMainMenu method

CHANGELOG.md, CONTRIBUTING.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package-lock.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.e2e.ts, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.scss, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.spec.ts, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx, stencil-workspace/src/components/modus-progress-bar/readme.md, stencil-workspace/storybook/package-lock.json, stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx
Add a new size input property to the Modus Progress Bar which takes either 'default' or 'compact' to change the size of the progress bar.
Closes #426
Manually, unit, and e2e tested.
=> Add 'compact' size option to the progress bar

CONTRIBUTING.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
Add required engines to the `package.json`. If the required engines are not in use, a warning is shown in the command line.
Closes #455 
This code has been tested manually by running `install` with required and inadequate versions.
=> Set required engines: Node & NPM CLI

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/icons/icon-cancel.tsx, stencil-workspace/src/components/icons/icon-upload-cloud.tsx, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.e2e.ts, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.spec.ts, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx, stencil-workspace/src/components/modus-file-dropzone/readme.md, stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone.stories.tsx, stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Add the File Dropzone component. Since this component was hard to write tests for (creating Files is not easy), and it feels subject to change, minimal tests were written.
Closes #421 
Minimal unit and e2e tests. Manual testing through the Storybook site.
=> Add File Dropzone component

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-file-dropzone/readme.md, stencil-workspace/storybook/package-lock.json, stencil-workspace/storybook/package.json, stencil-workspace/tsconfig.json
Update dependencies for the Stencil Workspace and the Storybook
I've built, and ran the tests for both the Stencil Workspace, and Storybook
=> Update Stencil Workspace and Storybook dependencies

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-modal/modus-modal.scss, stencil-workspace/src/components/modus-modal/modus-modal.spec.ts, stencil-workspace/src/components/modus-modal/modus-modal.tsx, stencil-workspace/src/components/modus-modal/readme.md, stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
Add an input to change the Modus Modal's z-index
=> Add input to change Modus Modal's z-index

stencil-workspace/package.json
Add `README.md` to npm package
Fixes #497
N/A
=> Add README to npm package

stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion.stories.tsx, stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx, stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx, stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx, stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx, stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs.stories.tsx, stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Partial fix for #511
Locally tested with Edge v102 (Windows 10)
=> Add Canvas Options for Components

stencil-workspace/storybook/package-lock.json, stencil-workspace/storybook/package.json
=> Update Storybook to latest version

stencil-workspace/.prettierrc, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/storybook/stories/components/modus-badge/modus-badge.stories.tsx, stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx, stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx, stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone.stories.tsx, stencil-workspace/storybook/stories/components/modus-message/modus-message.stories.tsx, stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx, stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx, stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx, stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx, stencil-workspace/storybook/stories/components/modus-spinner/modus-spinner.stories.tsx, stencil-workspace/storybook/stories/components/modus-switch/modus-switch.stories.tsx, stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx, stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Prettier formatting and update Prettier to latest version.
=> Prettier Docs formatting

angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Add useful homepage, license, bugs, repository fields to `package.json`.
For: https://npmjs.com/package/@trimble-oss/modus-angular-components
Fixes #530
JSON validated with VS Code
=> Add useful homepage, license, bugs, repository fields to `package.json`

CHANGELOG.md, stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.spec.ts, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx, stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts, stencil-workspace/src/components/modus-modal/modus-modal.scss, stencil-workspace/src/components/modus-modal/modus-modal.tsx, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.spec.ts, stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx, stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx, stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx
I fixed a few things with this change:
1. Make sure Modal isn't too wide for mobile, and fix its centering
2. Moved the aria-labels for Progress Bar and Dropzone to the host components to resolve accessibility issues
3. Close the dropdown list when it is clicked outside of
- Fixes #529
- Fixes #506 
- Fixes #472 
- Fixes #460
Manually, and e2e test fixes.
=> Fix various bugs

CHANGELOG.md
- Format CHANGELOG with Prettier
- Remove broken links
- Add a 'View all releases at: https://github.com/trimble-oss/modus-web-components/releases/' note to top.
- minor markdown formatting updates
- Add missing changelog update for accordion-header change recently made
- moved `inputmode` changelog change to correct place
=> Fix broken links and formatting in CHANGELOG.md

CHANGELOG.md, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss, stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- Accordion items border change from 2px to 1px
- Accordion body font size change from 16px to 14px
- Remove _italic_ style from text input placeholder
- change disabled text input to lighter gray (from `$col_gray_3` to `$col_gray_1`)
- Correct checkbox border color (from `$col_gray_6` to `$col_gray_4`)
=> Accordion, checkbox and text-input CSS fixes

angular-workspace/projects/trimble-oss/modus-angular-components/package.json, react-workspace/package-lock.json, react-workspace/package.json
The React workspace package.json was sorted with https://github.com/keithamus/sort-package-json via https://marketplace.visualstudio.com/items?itemName=unional.vscode-sort-package-json.
I skipped updating `CHANGELOG.md` as this is a deps update and therefore not needed.
=> update `@trimble-oss/modus-web-component` package to latest version

stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss, stencil-workspace/src/components/modus-alert/modus-alert.scss, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.scss
used: stylelint-order
Note: I think this change can skip being added to Changelog due to how minor it is.
yes, CSS still compiles without issues or errors.
=> alpha-sort css

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
Upgrade the project's NPM package to 0.1.10.
=> Upgrade version to 0.1.10

.github/workflows/azure-static-web-apps-deploy.yml
The default static web apps config is automatically added to the repo. This PR updates the build commands as necessary.
It works! https://icy-ground-0374a1310-600.centralus.1.azurestaticapps.net/?path=/story/introduction-welcome--page
with GitHub Action deploy previews!
=> Update and rename azure-static-web-apps config

angular-workspace/angular.json, angular-workspace/package-lock.json, angular-workspace/package.json, angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/tsconfig.json, react-workspace/package-lock.json, react-workspace/package.json
Upgrade the `angular-workspace` to use Angular 14 (specifically 14.1.1). Update the Angular and React packages to use new naming convention.
References #614
=> Upgrade to Angular 14. Update package versions

stencil-workspace/storybook/package-lock.json, stencil-workspace/storybook/package.json
Update Storybook deps to latest version. (Dependabot wasn't updating them).
=> storybook addon updates

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts
Added an entry in changelog for content tree.
Markdown preview in VS code
=> Added an entry in changelog for content tree

CHANGELOG.md, stencil-workspace/src/components/modus-message/modus-message.scss
=> update info message bg-color

CONTRIBUTING.md, README.md, design/capability-design.md, stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx, stencil-workspace/storybook/stories/introduction/welcome.stories.mdx
Fixes #651
markdown renderer in VS Code
=> Various minor markdown formatting fixes and grammar/spelling fixes.

CHANGELOG.md, stencil-workspace/src/components/modus-modal/modus-modal.scss
A few CSS fixes for modals to match the style guide:
https://modus-web-components.trimble.com/?path=/docs/components-modal--default
- Set the correct border color
- add border to header and footer
- remove unnecessary font and color CSS rule on modal
=> Update modus-modal CSS

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-checkbox/readme.md, stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.models.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.scss, stencil-workspace/src/components/modus-data-table/modus-data-table.spec.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/src/components/modus-data-table/modus-data-table.utilities.ts, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-link.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx, stencil-workspace/src/components/modus-data-table/readme.md, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
The change includes new selection options and event, and a row double click event
References #655 
Manually, e2e.
=> Selection options/event, row double click event, display options

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
Upgrade the package version to 0.1.12.
=> Upgrade package version to 0.1.12

CHANGELOG.md, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-chip/modus-chip.e2e.ts, stencil-workspace/src/components/modus-chip/modus-chip.scss, stencil-workspace/src/components/modus-chip/modus-chip.spec.ts, stencil-workspace/src/components/modus-chip/modus-chip.tsx, stencil-workspace/src/components/modus-chip/readme.md, stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-chip/modus-chip.stories.tsx
And remove large Chips which aren't part of Modus (and had layout issues with border-radius anyway).
Fixes: #593
Making the changes in this PR were relatively simple, just replacing `large` with `small` and modifying the CSS.
=> Add small chips

CHANGELOG.md, stencil-workspace/src/components/modus-badge/readme.md, stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.models.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.scss, stencil-workspace/src/components/modus-data-table/modus-data-table.spec.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/src/components/modus-data-table/modus-data-table.utilities.ts, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-badge.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx, stencil-workspace/src/components/modus-data-table/readme.md, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
Add Badge cell type to Data Table and fix Link cell type sorting
References #655 
Manually, unit, and e2e.
=> Add Badge cell type to Data Table

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-data-table/modus-data-table.models.ts, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
Upgrade to 0.1.13, and fix Data Table type
=> Upgrade package version to 0.1.13

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-checkbox/modus-checkbox.e2e.ts, stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss, stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx, stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx, stencil-workspace/src/components/modus-checkbox/readme.md, stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
The small checkbox on [modus-web-components.trimble.com/?path=/docs/user-inputs-checkbox--default](https://modus-web-components.trimble.com/?path=/docs/user-inputs-checkbox--default) is not a Modus-approved size. This PR removes it.
Fixes #680
=> Remove small checkbox

CHANGELOG.md, stencil-workspace/package.json, stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
=> Fixed dropdown open/close issue

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Upgrade version to 0.1.17

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
Prep `package.json` and `CHANGELOG.md` for 0.1.18 release
=> Upgrade package to 0.1.18

CONTRIBUTING.md, angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
=> Upgrade Angular output to 0.1.18. Update output docs

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
References AB#415977
Add help icon to ModusNavbar in stencil-workspace. My 1st PR may miss some steps.
=> Add a link to Help site

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss, stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
References AB#415941
Modify modus-navbar-apps-menu to support app categories
=> App Switcher Organization

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-button/readme.md, stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx, stencil-workspace/src/components/modus-navbar/apps-menu/readme.md, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx, stencil-workspace/src/components/modus-navbar/profile-menu/readme.md, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/src/interfaces.d.ts, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Update the Profile Menu's UX. This change brings links to the menu, and a restructure of the user details.
This has been tested manually through the dev sandbox.
=> Update the Navbar's Profile Menu UX

.github/CODEOWNERS
=> Add  CODEOWNERS file

stencil-workspace/storybook/.storybook/main.js, stencil-workspace/storybook/.storybook/preview.js
=> Disable light and dark mode theme toggler in storybook pages until the components are ready

.github/workflows/super-linter.yml
=> Disable Typescript as we run ESLint separately before the build

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-tabs/modus-tabs.spec.ts, stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
Prep package to release version 0.1.23
=> Update package version to 0.1.23

CHANGELOG.md, stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
=> Fix Tooltip styles (vertical padding and bg color)

CHANGELOG.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-card/modus-card.e2e.ts, stencil-workspace/src/components/modus-card/modus-card.scss, stencil-workspace/src/components/modus-card/modus-card.spec.ts, stencil-workspace/src/components/modus-card/modus-card.tsx, stencil-workspace/src/components/modus-card/readme.md, stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
Update the Modus Card to contain styling props.
Resolves #839
It was tested in index.html
=> Added changes for modus-card component

stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.vars.scss, stencil-workspace/src/components/modus-badge/modus-badge.scss, stencil-workspace/src/components/modus-button/modus-button.scss, stencil-workspace/src/components/modus-chip/modus-chip.scss
Fixes a comment in [PR](https://github.com/trimble-oss/modus-web-components/pull/848#issuecomment-1308651188)
=> Dark mode - Rearrange CSS styles alphabetically

.github/workflows/super-linter.yml, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Storybook example update: Add broken avatar example
Fixes #392
Manually viewing the Storybook
=> Example for Navbar's Avatar initials fallback

stencil-workspace/src/components/modus-badge/modus-badge.scss, stencil-workspace/src/components/modus-navbar/modus-navbar.scss, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
References AB#433547
Change navbar icon size and hover color
=> Minor UX Enhancements

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Update package version to v0.1.25

CHANGELOG.md, stencil-workspace/package-lock.json, stencil-workspace/package.json
Update package to release version v0.1.26
=> Update package version to v0.1.26

stencil-workspace/package-lock.json, stencil-workspace/package.json
Fixes: https://github.com/trimble-oss/modus-web-components/issues/940
Azure SWA build completed: https://icy-ground-0374a1310-942.centralus.1.azurestaticapps.net/
=> Remove @types/puppeteer and @types/puppeteer-core

.github/workflows/sonar-scan.yml, sonar-project.properties
=> Add sonarqube scan GitHub Action

stencil-workspace/src/sample.html
issue detected by SonarQube
https://sonar.trimble.tools/project/issues?id=Modus.trimble%3AModusWebComponents&languages=css&open=AYWakiVNVFnzCDn7ZqQv&resolved=false
=> fix: Unexpected duplicate selector "div", first used at line 20

CHANGELOG.md, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-navbar/main-menu/modus-navbar-main-menu.scss, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.scss, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss, stencil-workspace/src/components/modus-toast/modus-toast.tsx, stencil-workspace/src/components/modus-toast/modus-toast.vars.scss, stencil-workspace/src/components/modus-toast/readme.md, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
Fixes [# 383](https://github.com/trimble-oss/modus/issues/383)
Preview: https://icy-ground-0374a1310-981.centralus.1.azurestaticapps.net/
Browser Chrome
=> Removed `tertiary` variant from Modus Toasts

.github/workflows/mend-scan.yml, wss-unified-agent.config
Fixes #967 
Made the scan run once on this PR before scheduling it for monthly. 
Status can be checked here: https://github.com/trimble-oss/modus-web-components/actions/workflows/mend-scan.yml
and https://saas.whitesourcesoftware.com/Wss/WSS.html#!project;id=8677011
=> Added Mend(White Source) GitHub action

CHANGELOG.md, CONTRIBUTING.md, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts, react-workspace/src/components/stencil-generated/index.ts, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss, stencil-workspace/src/components/modus-autocomplete/readme.md, stencil-workspace/src/components/modus-text-input/modus-text-input.scss, stencil-workspace/src/components/modus-text-input/readme.md, stencil-workspace/src/global/themes.scss, stencil-workspace/src/interfaces.d.ts, stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
Initial `modus-autocomplete` addition.
This component still needs to implement keyboard controls.
Fixes #424 
Manually, unit and e2e tests.
=> Add Autocomplete

CHANGELOG.md, stencil-workspace/src/components/icons/icon-chevron-down-thick.tsx, stencil-workspace/src/components/icons/icon-chevron-up-thick.tsx, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx, stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts, stencil-workspace/src/components/modus-content-tree/modus-content-tree.spec.tsx, stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss, stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
Update chevron down icon in Modus Accordion and Modus Content tree components
Also, fixed a bug which is about not changing the size of icons in compact mode.
Fixes #503 
Preview: https://icy-ground-0374a1310-982.centralus.1.azurestaticapps.net/?path=/docs/components-accordion--default
=> Fix Accordion icons

CHANGELOG.md, stencil-workspace/angular-value-accessor-bindings.ts, stencil-workspace/stencil.config.ts
Add value accessor configurations for Angular forms
Fixes #653 
Manually installed and tested the Angular components using these new value accessors
=> Support Angular Reactive Forms

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts, stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs.stories.tsx
=> Add 'Small' Modus Tabs example

stencil-workspace/.stylelintrc.json, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-button/modus-button.scss, stencil-workspace/src/global/themes.scss
- [Remove deprecated "stylelint-config-prettier"](https://github.com/prettier/stylelint-config-prettier#stylelint-config-prettier)
- Update stylelint-order plugin
- Remove deprecated rules from config
- Run stylelint
=> Update Stylelint to  v15

.github/workflows/azure-static-web-apps-deploy.yml
This specifies using Node v16 (otherwise it uses Node v18 which causes build to fail).
=> Fix Azure Deply Preview Build Steps

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts, stencil-workspace/src/components/modus-date-input/modus-date-input.scss, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx, stencil-workspace/src/components/modus-date-input/modus-date-input.vars.scss, stencil-workspace/src/components/modus-date-input/readme.md, stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.calendar.ts, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.helpers.ts, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.state.ts, stencil-workspace/src/global/themes.scss
Hey, @ryan-henness-trimble Thanks for the feedback comments on the date picker component [PR](https://github.com/trimble-oss/modus-web-components/pull/1019), current PR includes all the fixes for your comments except one.
=> Date Picker - Fix review comments

stencil-workspace/src/components/modus-date-input/modus-date-input.tsx, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.calendar.ts, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.helpers.ts, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.state.ts, stencil-workspace/src/index.html
Fix the missed comments from the [date picker PR](https://github.com/trimble-oss/modus-web-components/pull/1019)
=> Fix missed PR comments

stencil-workspace/src/components/modus-time-input/modus-time-picker.formatter.tsx, stencil-workspace/src/components/modus-time-input/modus-time-picker.tsx
A minor bug fix for auto-formatting to work fine.
=> Fix time picker auto formatting

.github/workflows/add-issues-to-modus-project.yml
This GitHub Action will automatically add new issues to Modus Project.
It uses: https://github.com/actions/add-to-project
=> Add Issues to Modus project GitHub Action

stencil-workspace/src/components/modus-alert/modus-alert.vars.scss, stencil-workspace/src/components/modus-badge/modus-badge.vars.scss, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-badge/modus-badge-storybook-docs.mdx
_Light and dark Mode Progress bar: outline is Gray (#6a6e79) 6 both in Figma and XD, but indicates a non-palette color on style guide "border: 1px solid #8c8b96"_
- **No change**
-  _Dark mode dark Alert outline should be changed from Gray 10 to Gray 8 #464B52_
- Light theme - no change
- Dark theme - border color is **changed** to #464b52**
-  _The frame color of the secondary Alert is inconsistent (Gray 8 in both kits vs. Gray 6 on site). should be Gray 8 #464B52 - _no change__
_Dark mode active Chip/solid should be Trimble Dark Mode Blue #019AEB, it is currently Trimble blue on Style Guide. Both Figma and XD is #019AEB_
**- Light theme - no change
- Dark theme - **changed** to #019AEB**
_Light mode badges - warning badges have incorrect yellow on Style Guide. Currently on Yellow Dark. …
=> Fix incorrect progress bar outline / alerts / active chip / badges states

stencil-workspace/src/components/modus-alert/modus-alert.vars.scss, stencil-workspace/src/global/themes.scss
Changed from Gray 8 to Gray 6
Fixes #1091 
=> Fix secondary alert border color

stencil-workspace/package-lock.json, stencil-workspace/package.json
Update package for a new version release - v0.1.37
=> Update package to v0.1.37

stencil-workspace/src/components/modus-date-input/modus-date-input.spec.tsx, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx, stencil-workspace/src/components/modus-date-input/utils/modus-date-input.formatter.tsx, stencil-workspace/src/components/modus-date-input/utils/modus-date-input.tokens.tsx, stencil-workspace/src/components/modus-switch/modus-switch.scss, stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
Date Input should now be able to support Month name display through tokens 'mmm' and 'mmmm'
=> Enable Modus Date Input to display a month name

angular-workspace/projects/trimble-oss/modus-angular-components/.browserslistrc
Improves browser coverage from 19% to 89%
REF: https://browsersl.ist/#q=%3E1%25%2Clast+3+Chrome+versions%2Clast+2+Firefox+versions%2Clast+2+Edge+major+versions%2Clast+3+Safari+major+versions%2Clast+3+iOS+major+versions%2Clast+3+ChromeAndroid+versions%2CFirefox+ESR%2Cnot+dead
=> Update `.browserslistrc` config for Angular

stencil-workspace/src/components/modus-date-input/modus-date-input.scss, stencil-workspace/src/components/modus-number-input/modus-number-input.scss, stencil-workspace/src/components/modus-select/modus-select.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.scss, stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss, stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- Change helper text from 10px to 11px
- Change helper text weight from normal to **600**
- Docs: Improve labels for examples
=> Improve Input Helper Text styles

stencil-workspace/stencil.config.ts, stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Fixes: #1228
npm run build works as expected
- The JSON works as expected (tested in VS Code by adding `"html.customData": ["vscode.html-custom-data.json"]` to my `.vscode/settings.json`.
=> Generate `html.customData` JSON file for VS Code autocomplete

angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Bump version for Modus Angular Components
=> Release v0.1.40-ng14

stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Fix for: https://modus-web-components.trimble.com/?path=/docs/introduction-getting-started--page#vs-code-code-completion
Fix can be previewed at: https://icy-ground-0374a1310-1248.centralus.1.azurestaticapps.net/?path=/docs/introduction-getting-started--page#vs-code-code-completion
=> Fix syntax highlighting issue

.gitignore, .vscode/extensions.json, .vscode/settings.json
For developers using VS Code and working on MWC it's  very helpful for everyone to have their code real-time formatted and linted to the projects specs. By adding recommend extensions for ESLint, Prettier, EditorConfig and cSpell we can help contributors format and lint their code early in the development process and can help reduce feedback loop by catching bugs early.
=> Add VS Code Recommended Extensions and Settings

stencil-workspace/src/components/modus-data-table/modus-data-table.scss, stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss, stencil-workspace/src/global/themes.scss
=> Header border and Hover color

angular-workspace/projects/trimble-oss/modus-angular-components/README.md, stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx, stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Fixes #1157 
Updated below pages:
- https://icy-ground-0374a1310-1260.centralus.1.azurestaticapps.net/?path=/docs/introduction-getting-started--page#recommendations
- https://icy-ground-0374a1310-1260.centralus.1.azurestaticapps.net/?path=/docs/framework-integrations-angular--page
=> Add a reference to Modus Angular Components in Storybook

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.scss, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/src/components/modus-tooltip/readme.md
=> Modus NavBar - Add tooltip to search button

stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
Fixes #1119 
Preview: https://icy-ground-0374a1310-1266.centralus.1.azurestaticapps.net/?path=/docs/components-side-navigation--default#modus-side-navigation-blue-theme
=> Fix animation issue in Modus Side navigation component

stencil-workspace/src/components/modus-data-table/constants/constants.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.scss, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-column-resizing-handler.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header-sort.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
Fixes # [#1168 ](https://github.com/trimble-oss/modus-web-components/issues/1168)
=> Column resizing keyboard navigation development

.github/workflows/google-chat-notifiy.yml
Adds https://github.com/marketplace/actions/google-chat-notification GitHub Action.
=> Add google-chat-notifiy GitHub Action

angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Bump version numbers for Angular release on npm
=> Release 0.1.42-ng14

stencil-workspace/src/components/modus-data-table/constants/constants.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
Fix pagination row per page issue when pagination is not enable.
=> Pagination issue fix

stencil-workspace/src/components/modus-modal/modus-modal.scss
- Locally with Edge v113 on Windows 10 Pro
- Deploy Preview: https://icy-ground-0374a1310-1322.centralus.1.azurestaticapps.net/?path=/story/components-modal--default
=> Fix for Incomplete border line for Modal header and footer

CONSIDERATIONS.md, CONTRIBUTING.md
I want to try to make it easier for developers to contribute to this project. This seems like a good start to a document that will help developers get back in to the context of Modus Web Components when making changes or reviewing new changes. Since most contributors/reviewers are not on this project full-time, this could help us freshen up on some of the guiding principles. 
Please let me know your thoughts! 😀
References #1331
=> Add `CONSIDERATIONS.md` doc

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-data-table/enums/modus-column-data-type.ts, stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-summary-row.tsx, stencil-workspace/src/components/modus-data-table/readme.md, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
Added cell renderer 
Fixes #1209 
=> Added cell value formatter

stencil-workspace/src/components/modus-pagination/enums/pagination-direction.enum.ts, stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts, stencil-workspace/src/components/modus-pagination/modus-pagination.scss, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
=> Added prev Next text option to modus pagination

angular-workspace/package.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
=> Add Engines to specify minimum version of Node in Package.json

stencil-workspace/src/components/modus-data-table/constants/constants.ts, stencil-workspace/src/components/modus-data-table/modus-data-table.scss, stencil-workspace/src/components/modus-data-table/parts/modus-data-table-pagination.tsx, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
Added props in modus pagination storybook and renamed comments for next and previous button text
=> Added props in modus pagination storybook

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Fix the issues caused by last [PR](https://github.com/trimble-oss/modus-web-components/pull/1376)
=> Fix the breaking issues in GitHub Issue templates

stencil-workspace/package-lock.json, stencil-workspace/package.json
Update version to v0.1.43
**This PR is waiting for completion/merge of**:
- https://github.com/trimble-oss/modus-web-components/pull/1377
=> Update package to v0.1.43

react-workspace/projects/test-react-v17/package-lock.json, stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx, stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
Update the React integration page in Storybook to mention the new React components library.
Chrome browser
- Storybook - React integration page
=> Update React Storybook page about the new Modus React Components library

angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Update versions in `package.json` to prepare for release
=> Release v0.1.44-ng14

stencil-workspace/src/components/modus-select/modus-select.e2e.ts, stencil-workspace/src/components/modus-select/modus-select.scss, stencil-workspace/src/components/modus-select/modus-select.spec.ts, stencil-workspace/src/components/modus-select/modus-select.tsx, stencil-workspace/src/components/modus-select/modus-select.vars.scss, stencil-workspace/src/global/modus-variables.scss, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
div was replaced with "select native" to address the modus select issue, and the keyboard navigation problem was resolved.
References #559 ,#1334
=> Fix Modus Select Accessibility issues and Keyboard Navigation

angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/projects/trimble-oss/modus-angular-components/package.json
=> Release v0.1.45-ng14

react-workspace/README.md, react-workspace/package-lock.json, react-workspace/package.json
Bump version and minor update to README
=> Release v0.1.43-17 (React)

stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Added missing control in storybook for modus table.
=> Added missing controls for modus table in storybook page

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts, react-workspace/react-17/src/components/stencil-generated/index.ts, react-workspace/react-18/src/components/stencil-generated/index.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-add.tsx, stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx, stencil-workspace/src/components/modus-dropdown/readme.md, stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx, stencil-workspace/src/components/modus-navbar/button-list/readme.md, stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss, stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.tsx, stencil-workspace/src/components/modus-navbar/button-menu/readme.md, stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.scss, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/src/interfaces.d.ts, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
=> Copy of [EPD-11105] Implement changes to + icon based on feedback #1341

stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts, stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
Fixes #1496 
Preview: https://icy-ground-0374a1310-1497.centralus.1.azurestaticapps.net/?path=/story/user-inputs-text-input--default
=> Add missing watch for Modus Text Input `value` prop

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts, react-workspace/react-17/src/components/stencil-generated/index.ts, react-workspace/react-18/src/components/stencil-generated/index.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/icons/icon-close.tsx, stencil-workspace/src/components/icons/icon-search.tsx, stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.scss, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.scss, stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx, stencil-workspace/src/components/modus-navbar/search-overlay/readme.md, stencil-workspace/src/components/modus-text-input/modus-text-input.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.tsx, stencil-workspace/src/components/modus-text-input/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Search - add overlay and search functionality to Modus bar
Fixes #1413 
=> [EPD-11101] Search - add overlay and search functionality to Modus bar

stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
=> Update the open github issues link in Modus Data Table deprecation warning message 

stencil-workspace/src/components/modus-table/constants/constants.ts, stencil-workspace/src/components/modus-table/modus-table.e2e.ts, stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/src/components/modus-table/modus-table.spec.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
Integrated modus select in data table
References #
=> Integrated modus select in data table

stencil-workspace/package-lock.json, stencil-workspace/package.json
Version numbers bumped in advance of releasing v0.1.46
=> Release v0.1.46

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/icons/icon-arrow-down.tsx, stencil-workspace/src/components/icons/icon-arrow-up.tsx, stencil-workspace/src/components/modus-table/constants/constants.ts, stencil-workspace/src/components/modus-table/models/column-drag-state.model.ts, stencil-workspace/src/components/modus-table/models/drag-position.model.ts, stencil-workspace/src/components/modus-table/modus-table.e2e.ts, stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/modus-table.vars.scss, stencil-workspace/src/components/modus-table/parts/header/modus-table-column-resizing-handler.tsx, stencil-workspace/src/components/modus-table/parts/header/modus-table-header-sort.tsx, stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-drag-item.tsx, stencil-workspace/src/components/modus-table/readme.md, stencil-workspace/src/components/modus-table/utilities/drag-and-drop.utility.tsx, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Implemented column reorder in Modus Table using keyboard navigation.
References #686 , #1425 , #1274 , #1488 , #1490 , #1489 , #1499  , #1510 , #1512
=> Modus Table - Column reorder using Mouse Interactions and keyboard navigation

stencil-workspace/src/components/modus-table/modus-table.scss
=> Fixed cell padding issue

react-workspace/react-17/src/components/stencil-generated/react-component-lib/utils/attachProps.ts, react-workspace/react-18/src/components/stencil-generated/react-component-lib/utils/attachProps.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts, stencil-workspace/src/interfaces.d.ts, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Fixes build errors appearing when using Modus Angular components,
=> Remove duplicate interfaces export and make tooltip nullable for Modus Navbar `buttons` property

.github/workflows/labeler.yml
The logic was wrong. Thanks GitHub Copilot for helping to fix!
GitHub Action VS Code extension verifies/validates for errors
=> Fix GitHub Labeler Action

.github/workflows/publish-angular.yml, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/README.md, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/README.md
Automate publishing Angular MWC packages to npm and GitHub reg
Unable to test properly but GitHub Actions VS Code extension has validated the syntax is correct
=> Automate publishing Angular MWC packages to npm and GitHub reg

package-lock.json, package.json
This adds a update-mwc-dependants in the project root. Running it will update MWC in both React and both Angular projects as well as running npm install (to update the lock files). This will reduce manual work done for each release and speed things up. ⚡ 
Note: This requires https://www.npmjs.com/package/npm-check-updates being installed. In the future perhaps we could change it to: npx npm-check-updates to not require a local install.
Tested locally. Works!
=> Add update script to root

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts, stencil-workspace/src/components/modus-modal/modus-modal.tsx, stencil-workspace/src/components/modus-modal/readme.md, stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
- In the modus modal component a new property "backdrop" is required.
- This would accept 3 values - true, false, "static"
- When the backdrop is "static" - the modal does not close when we click outside the modal.
- When the backdrop is false - the background of the modal is not an opaque screen, the background would be the same page, The modal would not also be closed once clicked outside the modal.
- When the backdrop is true ( default mode ) - the backdrop is an opaque image, as usual and the modal would close once clicked outside the modal.
- Tried integrating the modus modal without backdrop property, works fine.
- Integrated with backdrop property **static**, the modal did not close when clicked anywhere outside the modal.
-  Integrated with backdrop property **false**, the modal's …
=> Modal component - Added `backdrop='static'` option to allow clicking outside the Modal content

stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/src/components/modus-table/modus-table.spec.tsx, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/modus-table.vars.scss, stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
implement vertical and horizontal scrollbar for modus table.
References #1307
=> Modus Table scrollbar development

stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Fixes console error from the Modus Date(Range) Picker component.
References #1583 
Visit the Storybook page for the Modus Date range picker and open the developer console window using F12.
=> Fix console errors in Modus date picker

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-table/enums/index.ts, stencil-workspace/src/components/modus-table/enums/modus-table-column-data-type.ts, stencil-workspace/src/components/modus-table/models/modus-table-cell-link.ts, stencil-workspace/src/components/modus-table/models/modus-table-column.ts, stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/modus-table.vars.scss, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-content.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-expand-icons.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-formatter.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-link-element.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx, stencil-workspace/src/components/modus-table/parts/panel/modus-table-dropdown-menu/modus-table-dropdown-menu.scss, stencil-workspace/src/components/modus-table/readme.md, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Added a new column datatype to display hyperlinks.
References #1524
=> Modus Table - Added functionality for hyperlink

stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Update `package.json` for Release v0149

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release Angular & React updates (v0.1.49) 

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx, stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Add click events for custom Navbar buttons that fire the button's custom id
Closes #1624
Through an E2e test
=> Add click events for Navbar's custom buttons

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Bump versions to v0.1.50

stencil-workspace/src/components/modus-toast/modus-toast.scss
Using the cursor: pointer when hovering on the toast close icon.
References #1629 
Manually tested. All existing tests run successfully.
=> [NAV-220] show pointer when hovering in toast close icon

stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-refresh.tsx
=> Added Icon Refresh

stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
Render changes to min/max page
Closes #1645 
Manually and e2e.
=> Pagination Component: Render changes to min/max page

stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-download-line.tsx, stencil-workspace/src/components/icons/icon-tune.tsx
Adding the icons: download-line and tune
References #1098
Tested manually. All tests ran successfully.
=> [NAV-224] added download-line and tune icons

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-autocomplete/readme.md, stencil-workspace/src/components/modus-date-input/readme.md, stencil-workspace/src/components/modus-date-picker/readme.md, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/src/components/modus-table/constants/constants.ts, stencil-workspace/src/components/modus-table/enums/modus-table-cell-edit-type.ts, stencil-workspace/src/components/modus-table/enums/modus-table-column-data-type.ts, stencil-workspace/src/components/modus-table/models/modus-table-column.ts, stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/modus-table.vars.scss, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editable.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-expand-icons.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx, stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx, stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/modus-table-columns-visibility.tsx, stencil-workspace/src/components/modus-table/readme.md, stencil-workspace/src/components/modus-text-input/modus-text-input.tsx, stencil-workspace/src/global/themes.scss, stencil-workspace/src/index.html, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
=> Added inline edit functionality

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-text-input/modus-text-input.tsx, stencil-workspace/src/index.html
Integrate chip component in autocomplete component
References #1543
=> Added chip in autcomplete component

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss, stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx, stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.calendar.tsx
=> Fix for starting date within the week in the month view

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Bump versions for Angular and React releases
=> Bump version to v0.1.53

stencil-workspace/stencil.config.ts
…ects.
Fixes: #1658
Pushed to a temporary package on npm and verified that a component can be rendered.
=> Added stencil config that enables modus to be used in vite based projects

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-countdown-timer.tsx, stencil-workspace/src/components/icons/icon-timer-countdown.tsx
=> Add countdown timer Icon

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
(We skipped releasing v0.1.54)
=> Update version for Angular and React packages (v0.1.55)

.github/workflows/azure-static-web-apps-deploy.yml
Fix broken deploy previews. Issue reported at: `github.com/Azure/static-web-apps/issues/1282`
We have this fix live on many other repos already.
=> Fix azure-static-web-apps-deploy issue

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/test-ng14/angular.json, angular-workspace/test-ng14/package-lock.json, angular-workspace/test-ng14/package.json, angular-workspace/test-ng15/angular.json, angular-workspace/test-ng15/package-lock.json, angular-workspace/test-ng15/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, react-workspace/test-react-v17/package-lock.json, react-workspace/test-react-v18/package-lock.json
Version bumps for React and Angular releases.
=> Release v0.3.1 (React and Angular)

.github/ISSUE_TEMPLATE/feature_request.yml, CONTRIBUTING.md
Added references about Modus Styleguide in Contributing guidelines md file
=> Added references to Modus Styleguide in Contributing guidelines

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
- Release v0.4.0
- Fixes a couple of minor linting issues
- Minor dev deps updates
=> Release v0.4.0

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx, stencil-workspace/src/components/modus-date-input/utils/modus-date-input.formatter.tsx, stencil-workspace/src/components/modus-date-picker/modus-date-picker.e2e.ts, stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
=> Fix for modus-date-picker failing test

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0141 - React and Angular

stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx, stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts, stencil-workspace/src/components/modus-alert/modus-alert.scss, stencil-workspace/src/components/modus-alert/modus-alert.spec.ts, stencil-workspace/src/components/modus-alert/modus-alert.tsx, stencil-workspace/src/global/themes.scss
Fix for multiple issues, https://github.com/trimble-oss/modus-web-components/issues/1546, https://github.com/trimble-oss/modus-web-components/issues/1541, https://github.com/trimble-oss/modus-web-components/issues/1540, https://github.com/trimble-oss/modus-web-components/issues/1547, https://github.com/trimble-oss/modus-web-components/issues/1527
=> Fix incorrect padding and theme colors on various components

stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-shield.tsx, stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
Added Shield Icon
References #1788 
- [x ] Bug fix (non-breaking change which fixes an issue)
Put the modus-icon component into index.html with name="shield", ran npm install. npm start. icon displayed as expected
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] I have checked my code and corrected any misspellings
=> Add shield icon

stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-pencil.tsx, stencil-workspace/src/components/modus-date-input/modus-date-input.spec.tsx, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx, stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts, stencil-workspace/src/components/modus-modal/modus-modal.scss, stencil-workspace/src/components/modus-modal/modus-modal.spec.ts, stencil-workspace/src/components/modus-modal/modus-modal.tsx, stencil-workspace/src/components/modus-modal/readme.md, stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
=> Add custom footer slot for Modal component

.cspell.json, .gitignore, angular-workspace/ng14/angular.json, angular-workspace/ng14/package-lock.json, angular-workspace/ng15/package-lock.json, angular-workspace/test-ng14/package-lock.json, angular-workspace/test-ng14/package.json, angular-workspace/test-ng15/angular.json, angular-workspace/test-ng15/package-lock.json, angular-workspace/test-ng15/package.json, package.json, react-workspace/test-react-v17/package-lock.json, react-workspace/test-react-v17/package.json, react-workspace/test-react-v17/src/examples/ModusTableExamples.tsx, react-workspace/test-react-v18/package-lock.json, react-workspace/test-react-v18/package.json, react-workspace/test-react-v18/src/App.css, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-table/models/modus-table.models.ts, stencil-workspace/src/components/modus-table/models/row-actions.model.ts, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md, stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
Fix dev dep issues and fix some build errors
Also fixed Angular components build issue, `RowActions` type 
npm run build
=> Fix dev dep issues and fix some build errors

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/storybook/package-lock.json, stencil-workspace/storybook/package.json
+ Fixes a few minor dev dependency security-related issues.
=> Release v0.15.1

stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
Add null check and early exit.
References #1834
- [ X] Bug fix (non-breaking change which fixes an issue)
Local testing on storyboard
- [X ] My code follows the style guidelines of this project
- X[ ] I have performed a self-review of my own code
- [ X] My changes generate no new warnings
- [X ] New and existing unit tests pass locally with my changes
- [X ] I have checked my code and corrected any misspellings
=> Date Picker - Add null check and early exit

stencil-workspace/src/components/icons/icon-sun.tsx
=> Rename class name for sun icon

.cspell.json, .github/workflows/labeler.yml, stencil-workspace/storybook/public/storybook-styles.css
Fixes: #1155
Also fixes a few spelling config issues
:has is quite new but this works with latest Safari, Chrome, Edge and Firefox!
=> Docs: Set color-scheme: dark when in dark mode.

stencil-workspace/package-lock.json, stencil-workspace/package.json
Version number bump for release.
=> Release v0.6.0

react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Bump version numbers in `package.json`
=> Release v060 React

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Version bump for Angular and React release
=> Release v070 - React & Angular

stencil-workspace/src/components/icons/IconMap.tsx, stencil-workspace/src/components/icons/icon-pin.tsx, stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
Added Pin icon.
References #1897
Put the modus-icon component into index.html with name="pin", ran npm install. npm start. icon displayed as expected
=> Added Pin icon.

stencil-workspace/src/components/modus-switch/modus-switch.e2e.ts, stencil-workspace/src/components/modus-switch/modus-switch.scss, stencil-workspace/src/components/modus-switch/modus-switch.spec.tsx, stencil-workspace/src/components/modus-switch/modus-switch.tsx, stencil-workspace/src/components/modus-switch/modus-switch.vars.scss, stencil-workspace/src/components/modus-switch/readme.md, stencil-workspace/src/global/modus-variables.scss, stencil-workspace/storybook/stories/components/modus-switch/modus-switch-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-switch/modus-switch.stories.tsx
Switch UI is updated according to figma 1.2.19 and story book of switch is updated as well
References # #1878
Unit tests are done to check the size prop
=> Update Switch UI and Storybook

stencil-workspace/src/components/modus-switch/modus-switch.scss, stencil-workspace/src/global/modus-variables.scss
=> Update Switch size

stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Release v0.9.0

stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx, stencil-workspace/src/components/modus-navbar/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
- Add the tabindex on the help icon
- Handle enter key event on Signout.
References #1945
=> Add tabindex on help icon and Sign out, handle enter key event on Sign out

stencil-workspace/src/components/modus-alert/modus-alert.scss
References #1581 
Preview: https://icy-ground-0374a1310-1960.centralus.1.azurestaticapps.net/?path=/story/components-alert--default&args=ariaLabel:rthrth+rth+rth+
=> Change Alert to min-height

stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
=> Fix checkbox CSS when displayed in tables

stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Moved `span` tag into the `modus-tooltip`.
References #1968
=> Fix The search tooltip is not Accessible using the tab navigation

stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
https://e-builderinc.atlassian.net/browse/DK-1638
Adding the clearable feature to the search bar within the nav bar.
References [#2019](https://github.com/trimble-oss/modus-web-components/issues/2019)
=> Navbar: add clearable field to search bar

stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/src/components/modus-pagination/readme.md, stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
=> Pagination: Update activePage default value

stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.vars.scss, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
=> Navbar: Update label UI

stencil-workspace/src/components/modus-alert/modus-alert.tsx
Add role and aria-label to Close/dismiss button
Fixes: #2082
Locally with Edge v121 and NVDA on Windows 11
=> Alert: Add `role` and `aria-label` to Close/dismiss button

stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
Docs: Move Radio Group to User Inputs section
fixes: #2075 
Locally with Edge v121 on Windows 11 Pro.
=> Docs: Move Radio Group to User Inputs section

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
References https://github.com/trimble-oss/modus-web-components/issues/2081
https://e-builderinc.atlassian.net/browse/EPD-11996
=> Autocomplete: Allow user to scroll through items in the dropdown

stencil-workspace/src/components/modus-alert/modus-alert.scss, stencil-workspace/src/components/modus-alert/modus-alert.spec.ts, stencil-workspace/src/components/modus-alert/modus-alert.tsx
=> Alert: Icon shrinking issue

stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
I've changed the icon name, the previous name doesn't exist anymore.
References #2145
=> Table: Fix Row Action More Icon

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx, stencil-workspace/src/components/modus-sentiment-scale/readme.md, stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale.stories.tsx
Adding some minor tweaks on top of previous #2121 
References #
Leveraged storybook to test
=> Sentiment Scale: Minor code cleanup

stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
Fixes: #2161
Preview: https://deploy-preview-2163--moduswebcomponents.netlify.app/?path=/story/components-content-tree--custom-filter
Locally with Edge v121 on Windows 11
=> Docs: Content Tree Custom Filter Example allow `Esc` to clear input

stencil-workspace/src/components/modus-button/modus-button.spec.ts, stencil-workspace/src/components/modus-button/modus-button.tsx
=> Button: Remove `role=button`

stencil-workspace/src/components/modus-navbar/notifications-menu/modus-navbar-notifications-menu.scss, stencil-workspace/src/components/modus-navbar/notifications-menu/modus-navbar-notifications-menu.tsx
- Removed the header from notification menu
References #
#1012
=> Navbar: Removed notification header

stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
=> Docs: Fix Alert Doc Inconsistency

stencil-workspace/src/components/modus-icons/modus-icons.tsx, stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
- Updated onClick method from `onClick={this.onClick}` to `onClick={() => this.onClick()}`
References #
#2058
=> Icons: Update ModusIcon to emit iconClick

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts, stencil-workspace/src/components/modus-navbar/modus-navbar.tsx, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx, stencil-workspace/src/components/modus-navbar/profile-menu/readme.md, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- Added a property to give the option to have the sign out text from profile menu with any text
References #
#1603
=> Navbar: Allow for custom sign out text

stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Use correct `logoOptions` prop in the navbar storybook.
References #
Ran storybook locally.
=> Navbar: Use correct logoOptions prop in Navbar storybook

stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss, stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx, stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- Images should always have `alt` tag
- Images should always have height and width defined in HTML for improved rendering performance
Locally
=> Navbar: Apps Menu Image Accessibility & CSS fix

stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.scss, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss, stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
This is to resolve the outstanding PR for #2126. I corrected the icons used in both the pagination control and side nav and adjusted some styles for sidenav to make it work in both in both expanded and collapsed state and to align with style guide.  
I also:
- update the side nav's icons to use named icons instead of svg strings.  
- Fixed a javascript error in the side nav's storybook caused by parameters not being defaulted.
- Other minor changes I will highlight in comments
References #568
Relied on running storybook locally.
=> Pagination & Side Nav: Update to use correct chevron icons.

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Update version of Modus Web Components for React and Angular
=> Release v0.19.0 - Update React and Angular

stencil-workspace/src/components/modus-chip/modus-chip.scss, stencil-workspace/src/components/modus-chip/modus-chip.spec.ts, stencil-workspace/src/components/modus-chip/modus-chip.tsx
Use button element (instead of a semantically meaningless div)
References #
=> Chips: Use button element

stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
- Added aria-current="date" to calendar body's button
References #
#1978
=> Date picker: Update accessibility to set aria-current

angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/readme.md
Fix missing documentation on the table column visibility readme
References #2155
n/a
=> Docs: update table column visibility for max height

.github/workflows/publish-angular.yml, angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, package.json, stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx, stencil-workspace/stencil.config.ts
References #1588
Running local builds
=> Angular: Updating output targets

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/readme.md
=> Angular: Update components.d.ts properly

.github/workflows/publish-angular.yml
Updated yml to properly publish
References #1588 
Ran the workflow from my branch
=> Angular: Update publish yml

stencil-workspace/src/components/modus-slider/modus-slider.spec.ts, stencil-workspace/src/components/modus-slider/modus-slider.tsx, stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
Fixes: https://github.com/trimble-oss/modus-web-components/issues/598
Storybook
=> Slider: Accessibility fixes

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.22.0 - Updating package version
=> Release v0.22.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Release v0.22.0 - Updating packages for Angular and React
=> Release v0.22.0 - ng & React

stencil-workspace/storybook/stories/components/modus-slider/modus-slider-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
- remove duplicate `label`
- update accessibility guidelines
- Locally with Edge v123 on Windows 11
- https://deploy-preview-2328--moduswebcomponents.netlify.app/?path=/docs/components-slider--default
=> Docs: Slider docs fixes

stencil-workspace/src/components/modus-select/modus-select.spec.ts, stencil-workspace/src/components/modus-select/modus-select.tsx, stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
This links the selects to their labels.
Fixes: #2329
=> Select: Fix for Labels not being linked to the selects

stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
Fix broken radio-group component examples
References #
=> Docs: fix broken radio-group component examples

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.23.0 - Updating package version
=> Release v0.23.0

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx, stencil-workspace/src/components/modus-radio-group/readme.md, stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
Update documentation to:
* Include a link to a description of the `name` attribute for radio buttons
* Indicate that the default `size` is "medium"
References #2213
Manually verified in storybook
=> Radio group: Update documentation

stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts
Replace delays with waitForChanges in end-to-end tests in tooltips
This is just an improvement in the tests, not an actual bug fix/new feature.
=> Tooltip: Replace delays with waitForChanges in end-to-end tests

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.24.1 - Updating package version
=> Release v0.24.1

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.24.1 - ng & React

stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
=> Dropdown: Add control to docs

stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts, stencil-workspace/src/components/modus-modal/modus-modal.spec.ts, stencil-workspace/src/components/modus-modal/modus-modal.tsx, stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
* When not visible, role is not "dialog"
* When visible, has "aria-modal" attribute
* When not visible, "aria-label" is not present
* When not visible, "aria-hidden" is true
References #2076 (note: I am leaving the final bullet point off, as that is a breaking change and I am not an employee/owner and there seems to be ambiguity as to whether or not we should implement that change.)
E2E tests
=> Modal: Accessibility updates

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-toast/modus-toast.spec.ts, stencil-workspace/src/components/modus-toast/modus-toast.tsx, stencil-workspace/src/components/modus-toast/readme.md, stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
Make 'role' configurable on `modus-toast`.
References #2143 (there's no issue for this individual feature)
Added a unit test
=> Toast: make 'role' configurable.

stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts, stencil-workspace/src/components/modus-content-tree/modus-content-tree.spec.tsx, stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
- Update icon
References #2394
=> Content Tree: Update chevron icon

stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
=> Navbar : Help Icon tab navigation

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts, stencil-workspace/src/components.d.ts
Updating type definitions
References #1011
Compiled
=> Navbar: add missing notificationCount definition

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.25.0 - Updating package version
=> Release v0.25.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.25.0 - ng & React

stencil-workspace/stencil.config.ts
This means that CSS is compiled and added to dist folder in dev mode which means it is hot-reloadable in Storybook serve mode. Makes development much faster!
References #2442
=> DevOps: Build Stencil Dist Files in Dev Mode

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.26.0 - Updating package version
=> Release v0.26.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-button-group/modus-button-group.tsx, stencil-workspace/src/components/modus-button-group/readme.md
=> Release v0.26.0 - ng & React

stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.vars.scss, stencil-workspace/src/global/themes.scss
Fix for Accordion Item left-border color CSS variable
https://deploy-preview-2459--moduswebcomponents.netlify.app/?path=/story/components-accordion--default
=> Accordion: Fix Item left-border color CSS variable

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.261 - Updating package version
=> Release v0.26.1

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.26.1 - ng & React

stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts, stencil-workspace/src/components/modus-dropdown/modus-dropdown.scss, stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
Added a CSS class to the dropdown's containing div that is only present when disabled, added CSS to that class to disable pointer events.
References #2464
=> Dropdown: Prevent pointer events from occurring when disabled.

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.27.0 - Updating package version
=> Release v0.27.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, stencil-workspace/src/components/modus-switch/readme.md
=> Release v0.27.0 - ng & React

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts
Release v0.28.0 - Updating package version
=> Release v0.28.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.28.0 - ng & React

stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/modus-table-columns-visibility.scss
=> Table: Align Apply and Cancel buttons towards the right in the column visibility panel

stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts, stencil-workspace/src/components/modus-pagination/modus-pagination.scss, stencil-workspace/src/components/modus-pagination/modus-pagination.spec.ts, stencil-workspace/src/components/modus-pagination/modus-pagination.tsx, stencil-workspace/src/components/modus-table/modus-table.e2e.ts
- Integrated the native button inside the pagination list.
References 
Fix #2043
=> Pagination - Added button to lists

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components.d.ts
Release v0.29.0 - Updating package version
=> Release v0.29.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.29.0 - ng & React

.github/workflows/codeql.yaml
- Rename action to "codeql" (default name)
- Widen the issues to scan for with the `security-and-qualit`y mode (See this for deatils: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs)
- Scan on every PR and remove scheduled scan (not needed if scan is on every PR)
- Scan on TypeScript as well as JavaScript
=> CodeQL GitHub Action Improvements

stencil-workspace/src/components/modus-tabs/modus-tabs.scss, stencil-workspace/src/components/modus-tabs/modus-tabs.spec.ts, stencil-workspace/src/components/modus-tabs/modus-tabs.tsx, stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs.stories.tsx
Updated tabs to also display icons
Updated test
Updated storybook
References #2537
=> Tabs: Add icon support

stencil-workspace/src/components/modus-date-input/modus-date-input.scss, stencil-workspace/src/components/modus-number-input/modus-number-input.scss, stencil-workspace/src/components/modus-select/modus-select.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.scss, stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Inputs: Set border for disabled state to transparent
Locally with Edge v125
=> Inputs: Set border for disabled state to transparent

stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts, stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts, stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Add delay of 500ms on hover
lazy tooltip initialization for better performance
References 
Fixes #2535
=> Tooltip: performance optimization

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.30.0 - ng & React

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss, stencil-workspace/src/components/modus-date-input/modus-date-input.scss, stencil-workspace/src/components/modus-date-input/modus-date-input.vars.scss, stencil-workspace/src/components/modus-number-input/modus-number-input.scss, stencil-workspace/src/components/modus-number-input/modus-number-input.vars.scss, stencil-workspace/src/components/modus-select/modus-select.scss, stencil-workspace/src/components/modus-select/modus-select.vars.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.scss, stencil-workspace/src/components/modus-text-input/modus-text-input.vars.scss, stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss, stencil-workspace/src/components/modus-time-picker/modus-time-picker.vars.scss, stencil-workspace/src/global/themes.scss
Fixes: #2579
Locally by copying `sample.html` to the build dist and opening in a local server.
=> Inputs: Fix focus border CSS styles

stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
=> Docs: Fix broken link to Modus Icons site

.prettierignore, .vscode/settings.json
- Don't ignore CSS, HTML, CSS, MDX or Stories TSX
Ran `npm run prettier` - works great! I didn't commit all changed files to this PR, instead they can be done gradually as each file is updated.
=> Autoformats code with Prettier

stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Addressed the PR comments for #2582 
References 
Ticket #1602
=> Table: Updated documentation for custom sorting function

stencil-workspace/src/components/modus-button/modus-button.vars.scss, stencil-workspace/src/global/themes.scss
=> Update Button Borderless secondary color in themes

stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
- Added crumbClick to action tab which triggers on clicking a Bread crumb tab
References
Fixes #2637 
https://deploy-preview-2638--moduswebcomponents.netlify.app/?path=/story/components-breadcrumb--default
=> BreadCrumb:  Add handling of event "crumbClick"

stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
- updated the size property from `large` to `large | medium`
References 
Fixes #2200
=> AutoComplete: size property update for storybook

stencil-workspace/src/components/modus-modal/modus-modal.scss, stencil-workspace/src/global/modus-variables.scss
Preview:
https://deploy-preview-2680--moduswebcomponents.netlify.app/?path=/story/components-modal--default
Figma:
=> Modal: Change header title to `font-weight: 700`

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.34.0 - Updating package version
=> Release v0.34.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.34.0 - ng & React

stencil-workspace/src/components/modus-pagination/modus-pagination.scss, stencil-workspace/src/global/themes.scss
Replaced the hardcoded color of the text with the variable and changed color variable values to match the colors from the Modus Figma file
References #2702 
Preview:
https://deploy-preview-2703--moduswebcomponents.netlify.app/?path=/story/components-pagination--default
=> Pagination: Nonactive pages number visible in dark mode

stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts, stencil-workspace/src/components/modus-alert/modus-alert.scss, stencil-workspace/src/components/modus-alert/modus-alert.spec.ts, stencil-workspace/src/components/modus-alert/modus-alert.tsx, stencil-workspace/src/components/modus-alert/modus-alert.vars.scss, stencil-workspace/src/global/modus-variables.scss, stencil-workspace/src/global/themes.scss, stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-alert/modus-alert.stories.tsx
Fixes: #2626
Locally with Edge on Windows 11
https://deploy-preview-2724--moduswebcomponents.netlify.app/?path=/docs/components-alert--default#alert
=> Alerts: Update Styles

stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
- update onClick to buttonClick event in react documentation
References 
Fixes 
#2716
=> StoryBook: Documentation update for react button click 

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.34.0 - Updating package version
=> Release v0.35.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, react-workspace/test-web-components/package-lock.json, react-workspace/test-web-components/package.json
=> Release v0.35.0 - ng & React

CONTRIBUTING.md
Included "npm run build" to the "Runing the App" section to avoid getting an error.
The instructions in the CONTRIBUTING.md under the 'Getting Started' section for 'Running the App.' After the contributor has installed the project's packages, they must run `npm run build` from the stencil directory.  The motivation was to fix an issue that I encountered when trying to contribute to the this repository for the first time. 
References #2730
=> Updated Instructions "Running the App"

stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
=> Button - replace onclick with buttonClick for react docs

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.36.0 - Updating package version
=> Release v0.36.0

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, react-workspace/test-web-components/package-lock.json, react-workspace/test-web-components/package.json
=> Release v0.36.0 - ng & React

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Updated ng & React package versions
=> Release v0.36.0 - ng react

.github/workflows/super-linter.yml
Adds `VALIDATE_TSX: false`. This fixes the reason for the failed linting.
See: https://github.com/trimble-oss/modus-web-components/actions/workflows/super-linter.yml?query=is%3Afailure for details.
=> Update Super Linter

stencil-workspace/src/components/modus-badge/modus-badge.scss
Update small-size to have 2px border radius
This change matches Figma and the style guide
Preview:
https://deploy-preview-2791--moduswebcomponents.netlify.app/?path=/story/components-badge--default&args=size:small
=> Badge: Update small-size to have 2px border radius

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.37.0 - Updating package version
=> Release v0.37.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.37.0 - ng & React

stencil-workspace/src/components/modus-table/modus-table.scss
=> Table checkbox row selection overlapping issue

.github/workflows/super-linter.yml, stencil-workspace/storybook/.storybook/preview.js, stencil-workspace/storybook/stories/introduction/accessibility.stories.mdx
Fixes: #2704
Locally with Edge on Windows 11
https://deploy-preview-2844--moduswebcomponents.netlify.app/?path=/docs/introduction-accessibility--page
=> Docs: Add Accessibility page

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.38.0 - Updating package version
=> Release v0.38.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.38.0 - ng & React

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.39.0 - Updating package version
=> Release v0.39.0

angular-workspace/ng14/package-lock.json, angular-workspace/ng14/package.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/package-lock.json, angular-workspace/ng15/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/package-lock.json, angular-workspace/ng16/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/package-lock.json, angular-workspace/ng17/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
=> Release v0.39.0 - ng & React

stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
=> Button-group: fix reset state for single selection

stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts, stencil-workspace/src/components/modus-modal/modus-modal.tsx
=> Modal : closed event infinite loop fix

stencil-workspace/src/components/modus-navbar/modus-navbar.scss, stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss
=> Navbar:  profile menu icon background to be transparent

stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
=> List : Add missing property(leftIcon) to documentation

stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
=> Side Navigation: Update prop name to menuIcon from menuIconUrl

stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
- Added custom placement property to canvas
References 
Fixes #2799
=> DropDown : Add customPlacement to docs

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
References 
Fixes #1279 
https://deploy-preview-2923--moduswebcomponents.netlify.app/?path=/story/user-inputs-autocomplete--default&args=disabled:true
=> Autocomplete: add disabled feature for auto-complete 

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
=> Autocomplete: custom options duplicate chips issue 

stencil-workspace/src/components/modus-button/readme.md, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.e2e.ts, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss, stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx, stencil-workspace/src/components/modus-file-dropzone/readme.md, stencil-workspace/src/sample.html, stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion.stories.tsx, stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx, stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx, stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx, stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx, stencil-workspace/storybook/stories/components/modus-message/modus-message-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-message/modus-message.stories.tsx, stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx, stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx, stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx, stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker.stories.tsx, stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel-storybook-docs.mdx, stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
- Fixes the flaky test
- Fixes lint errors
References 
Fixes #2924
=> FileDropzone  : Fix reset button loading time

stencil-workspace/package-lock.json, stencil-workspace/package.json
Release v0.40.0 - Updating package version
=> Release v0.40.0

angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json
Bump ng & react package versions
=> Release v0.40.0 - ng & React

stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx, stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
=> Remove `aria-checked` (not needed)

stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
=> DatePicker: bug with errorText

stencil-workspace/src/components/modus-select/modus-select.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx, stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
- Modified the logic to set selected value to compare options by value
`option[optionsDisplayProp]`
References 
Fixes #2878
=> Select: Update logic to not compare selected value by reference

stencil-workspace/src/components/modus-table/modus-table.tsx
- Updated setting pagination logic when data is modified
References 
Fixes #2836
=> Table: Fix Manual Pagination issues

stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
- Added null check to optionsDisplayProp
References 
Fixes #2965
=> Table: Add null check to table pagination's optionsDisplayProp

stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
=> Table : Fix cancel icon in row action column

stencil-workspace/src/components/modus-table/modus-table.tsx
=> Table: manual pagination and rows expandable conflict issue

stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx, stencil-workspace/src/components/modus-radio-group/modus-radio-group.e2e.ts, stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx, stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
=> Radio group: keyboard navigation for next and previous option

stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
- Modified css of content ActionBar buttons
References 
Fixes #2162
=> Content Tree: ActionBar Buttons Modify Style

stencil-workspace/storybook/public/storybook-styles.css, stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
- Added dark theme colors to action bar
References 
Fixes #1466
=> Content Tree: Add dark theme colors to action bar

stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss, stencil-workspace/src/components/modus-table/modus-table.scss, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
Centered row selection checkbox left-right and top-bottom
References #2978
Using `index.html` and the storybook.
=> Table: Centered row selection checkbox for the table

stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx
- Added MDN Link for information on valid file type specifiers
References 
Fixes #2691
=> FileDropzone: Update docs with MDN Link for valid file type specifiers

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-tabs/modus-tabs.scss
Updates `Stylelint`& `stylelint-config-standard-scss` to latest versions and runs `npm run lint-css`.
=> Bump cross-spawn from 15.11.0 to 16.10.0 in /stencil-workspace

stencil-workspace/src/components/modus-checkbox/modus-checkbox.e2e.ts, stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
=> Checkbox: Fix Space bar Functionality for Toggle Behavior

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-button/modus-button.e2e.ts, stencil-workspace/src/components/modus-button/modus-button.scss, stencil-workspace/src/components/modus-button/modus-button.spec.ts, stencil-workspace/src/components/modus-button/modus-button.tsx, stencil-workspace/src/components/modus-button/modus-button.vars.scss, stencil-workspace/src/components/modus-button/readme.md, stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx, stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
References 
Fixes #1439 
https://deploy-preview-2871--moduswebcomponents.netlify.app/?path=/story/components-button--danger-button&args=criticalAction:true
=> Button: add critical action feature

stencil-workspace/src/components/modus-message/modus-message.vars.scss, stencil-workspace/src/global/themes.scss
=> Message: message text color code fix in dark mode 

stencil-workspace/src/components/modus-table/modus-table.e2e.ts, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx, stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx, stencil-workspace/src/lang/translations.ts
- Follows RFC 5646 pattern
- Setting default  lang to document parent instead of navigator  
References 
Fixes #3045
=> Table: language translation based on RFC 5646

stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
- Defined disablecloseonselect property in the default template of docs
References 
Fixes #3087
=> DropDown: Define disablecloseonselect property in docs 

react-workspace/test-react-v18/package-lock.json, react-workspace/test-react-v18/package.json, react-workspace/test-web-components/package-lock.json, react-workspace/test-web-components/package.json
=> Fix Security issues

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss
=> Autocomplete: Enable clear icon for multiple selection

angular-workspace/test-ng15/package-lock.json, angular-workspace/test-ng15/package.json
This addresses many minor security issues reported by Mend.
=> npm audit fix (test-ng15)

stencil-workspace/src/components/modus-alert/modus-alert.scss, stencil-workspace/src/components/modus-alert/modus-alert.vars.scss, stencil-workspace/src/global/themes.scss
References #
https://deploy-preview-3161--moduswebcomponents.netlify.app/?path=/docs/components-alert--docs
=> Alert: Fix Icon Colors

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-chip/modus-chip.scss, stencil-workspace/src/components/modus-chip/modus-chip.spec.ts, stencil-workspace/src/components/modus-chip/modus-chip.tsx, stencil-workspace/src/components/modus-chip/readme.md
References 
Fixes #2698 
https://deploy-preview-3163--moduswebcomponents.netlify.app/?path=/story/user-inputs-autocomplete--multiple-selection&args=clearable:!true;value[0]:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;options[0].value:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
=> Autocomplete: chip fix overlapping issue

.cspell.json, stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx, stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-resizing-handler.tsx, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Table documentation misspelling
References #
`npm run spellcheck` completes without errors from CLI on root.
=> Docs: Table documentation misspelling

stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss, stencil-workspace/src/components/modus-table/modus-table.scss
No need for these - this is handled by Autoprefixer
Yes, locally.
=> Remove unneeded CSS vendor prefixes

stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss
References 
Fixes #2951 
BUG (initials don't show):
https://modus-web-components.trimble.com/?path=/docs/components-navbar--docs#failed-avatar-initials-fallback
FIX (initials show):
https://deploy-preview-3183--moduswebcomponents.netlify.app/?path=/docs/components-navbar--docs
=> Navbar: fix profile menu initials background color 

stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx, stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss
=> Autocomplete: search text highlight feature

stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
References 
Fixes #3192 
https://deploy-preview-3215--moduswebcomponents.netlify.app/?path=/story/user-inputs-date-picker--date-range
=> Date Picker: remove error message on valid date 

stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Release v1.5.1

stencil-workspace/src/components/modus-table/modus-table.tsx
- Prevented multiple emissions of rowSelectionChange
References 
#3270
=> Table: Prevent rowselectionchange from emitting twice

stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts, stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx, stencil-workspace/src/components/modus-dropdown/readme.md, stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx, stencil-workspace/src/components/modus-navbar/modus-navbar.scss
=> Navbar: Fix dropdown UI issues with slots

stencil-workspace/src/components.d.ts, stencil-workspace/src/components/modus-table/modus-table.tsx, stencil-workspace/src/components/modus-table/readme.md, stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
=> Table:  Add a method to select or deselect rows

stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts, stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
=> DateInput: Display an error for invalid dates in the DateInput

stencil-workspace/package-lock.json, stencil-workspace/package.json
=> Release v1.7.0

design/capability-design.md, sonar-project.properties, stencil-workspace/stylelint.config.mjs
- Fix markdown links
- Fix Stylelint config
- Fix SonarQube key (MWC v2 uses the one that this is using so needed to update to keep them unique)
=> Lint Fixes

stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss, stencil-workspace/stylelint.config.mjs
Fixes issue reported by Kabir B.
=> Navbar: Fix overlapping text on profile username

.github/workflows/publish-angular.yml
- Adds Angular 19 support
- Removes Angular 15 support
=> GitHub Action workflow: Adds Angular 19 support

stencil-workspace/package-lock.json, stencil-workspace/package.json, stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx, stencil-workspace/src/components/modus-data-table/modus-data-table.tsx, stencil-workspace/src/components/modus-slider/modus-slider.tsx
I ran Prettier on all code too.
=> Release v1.8.1

CONTRIBUTING.md, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng18/package-lock.json, angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng19/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng19/projects/trimble-oss/modus-angular-components/package.json, angular-workspace/ng20/projects/trimble-oss/modus-angular-components/package-lock.json, angular-workspace/ng20/projects/trimble-oss/modus-angular-components/package.json, react-workspace/react-17/package-lock.json, react-workspace/react-17/package.json, react-workspace/react-18/package-lock.json, react-workspace/react-18/package.json, react-workspace/react-19/package-lock.json, react-workspace/react-19/package.json
Also fixed `npm audit fix` issues... reducing flagged Dependabot security issues from 87.
=> Release v1.8.1 -Angular & React
