trimble-oss/modus-web-components

- .editorconfig
- README.md
- storybook/public/storybook-styles.css
- Fix for links not appearing in blue (fixes: #328 )
- change URL on README to production URL rather than Netlify.app one
- Add alt tags to images (accessibility)
- `.editorconfig` minor fix so trailing spaces are trimmed in markdown files
> Readme markdown fixes

- storybook/public/storybook-styles.css
- storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
- storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
- storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
- storybook/stories/components/modus-slider/modus-slider-storybook-docs.mdx
- storybook/stories/components/modus-spinner/modus-spinner-storybook-docs.mdx
- storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx
- storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
- storybook/stories/components/modus-tooltip/modus-tooltip-storybook-docs.mdx
CSS added to tables to make 1st column equal width (looks a bit neater).
partial fix for #370
This PR updates half of them. I'll tackle the others in a later PR
> Table formatting fixes

- .github/pull_request_template.md
When someone creates a pull request template to the modus-web-components repository, project contributors will automatically see the template's contents in the pull request body.
Please review and let me know if anything needs to be changed / added / removed.
References #378
> create a pull_request_template.md for the project

- package.json
- src/components.d.ts
- src/components/modus-badge/modus-badge.scss
- src/components/modus-list-item/modus-list-item.e2e.ts
- src/components/modus-list-item/modus-list-item.scss
- src/components/modus-list-item/modus-list-item.spec.ts
- src/components/modus-list-item/modus-list-item.tsx
- src/components/modus-list-item/readme.md
- src/global/modus-variables.scss
- storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
This PR covers two items:
1. Updating the `modus-badge` to have a font-weight of 700.
2. Adding a third option to the `modus-list-item` component. This changes the default 'standard' size, and adds a new 'large' size.
Fixes #394
Closes #397 
This has been tested manually in the StencilJS dev and Storybook environments, as well as unit and e2e code tested.
> Change `modus-badge` weight. Add new 'standard' `modus-list-item` size option

- README.md
- storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
- storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Updated the README badge links to link to appropriate pages.
Updated the Navbar's implementation info about the avatar falling back to initials if it fails to load. Removed the 'help' menu from the examples as that is no longer an option.
I was having issues getting the initial fallback to work when there were two Navbars on the same page. So I will only link this as a Reference to that Issue, not a Closer.
Closes #362
References #392 
Manually running the Storybook site
> Update README badge links. Update Navbar docs info.

- CHANGELOG.md
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/src/components/modus-text-input/readme.md
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Add a `type` input the Modus Text Input, which allows for either 'text' or 'password', changing the wrapped input type.
Closes #486
Manually, unit and e2e.
> Add password option to Modus Text Input

- CHANGELOG.md
- stencil-workspace/package.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
- stencil-workspace/src/components/modus-toast/readme.md
- stencil-workspace/src/interfaces.d.ts
Added JSX output for React Component generation. Fixed the type of the Toast's ariaLabel, it shouldn't have been boolean.
Running tests, and manually building/packing the package
> Fixed Toast's ariaLabel, and added JSX output

- CHANGELOG.md
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/.prettierrc
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/src/components/modus-text-input/readme.md
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Fixes: https://github.com/trimble-oss/modus-web-components/issues/533
Tested locally
> Adds `inputmode` to modus-text-input

- stencil-workspace/storybook/public/storybook-styles.css
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
Change dropdown example from 1 to 3 items to make it more real-world usage looking... also fix for z-index issue on code blocks.
PREVIEW: https://deploy-preview-558--modus-web-components.netlify.app/?path=/docs/components-dropdown--default
> Change dropdown example from 1 to 3 items

- CHANGELOG.md
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
- stencil-workspace/src/components/modus-modal/modus-modal.scss
- stencil-workspace/src/components/modus-modal/modus-modal.spec.ts
- stencil-workspace/src/components/modus-modal/modus-modal.tsx
- stencil-workspace/src/components/modus-text-input/readme.md
- stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
- Correct font size for accordion header
- Correct font size for modal header and body text
- Added `role="button"` and `aria-label="Close"` to Modal Close button (accessibility fix)
Locally with Edge v103 on Windows 10
> Accordion and Modal spec updates

- CHANGELOG.md
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.scss
- stencil-workspace/src/components/modus-pagination/modus-pagination.scss
- Add border-radius to Modus Dropdowns
- Modus number inputs has correct color bg when disabled
- Pagination active color is now `$col_blue_light`
locally windows 10 Edge v103
> Styles synced to match Modus style guide

- CHANGELOG.md
- stencil-workspace/src/components/modus-chip/modus-chip.tsx
- stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
Fix for: Accessibility: Chips images don't have alternate text.
This adds an empty alt tag. I considered adding an option to add a custom alt text to the image but deemed it to not be worthwhile for now as the image is decorative and the text in the chip should suffice.
This PR also converts docs tables for chips to markdown tables.
with fix:
without fix:
> Add empty alt tag to images in chips

- CHANGELOG.md
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
- stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
This removes the unneeded `role="region"` attribute from accordion-items.
See issue #594 for details
Netlify preview: https://deploy-preview-595--modus-web-components.netlify.app/
> Fix role="region" a11y issue with accordion-items

- stencil-workspace/src/components/modus-radio-group/modus-radio-group.scss
- stencil-workspace/src/components/modus-radio-group/modus-radio-group.spec.ts
- stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
Change `ul` to `div` to fix a11y issue with radio button group.
Edge v103 on Windows 10
Screenshot of change: (note: no a11y violations!)
> change ul to div to fix a11y issue with radio button group

- CHANGELOG.md
- stencil-workspace/src/components/modus-chip/modus-chip.scss
Changes to match Modus Bootstrap and Styleguide:
https://modus-bootstrap.trimble.com/components/chips/
Screenshot of change (using Devtools to make it 'active':
> Active State changes for Chips

- CHANGELOG.md
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-button/modus-button.e2e.ts
- stencil-workspace/src/components/modus-button/modus-button.scss
- stencil-workspace/src/components/modus-button/modus-button.spec.ts
- stencil-workspace/src/components/modus-button/modus-button.tsx
- stencil-workspace/src/components/modus-button/readme.md
- stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
Remove (yellow) warning button color and make primary the default
Change button colors for docs
Fixes #635
> Update available button styles

- stencil-workspace/package-lock.json
- stencil-workspace/package.json
This was displaying in CLI log as a warning when included. Build completes successfully with it removed.
Fixes #613 
Note: I didn't add to CHANGELOG due to it being a dependency change which we usually don't mention.
Build completes.
> Remove unneeded `@types/autoprefixer`

- stencil-workspace/src/components/modus-spinner/modus-spinner.scss
- stencil-workspace/storybook/stories/components/modus-spinner/modus-spinner-storybook-docs.mdx
Fixes: #642
Note: I didn't update CHANGELOG - maybe not needed for minor docs updates?
> fix for Spinners spacing issue in loading button example

- CHANGELOG.md
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
> Add `aria-current="page"` to final breadcrumb

- CHANGELOG.md
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- clear button is now taller for improved accessibility as a tap target (by adding CSS min-height: 1.5rem)
- button was actually just a span with no semantic markup. so we added `role="button"`
- Add `aria-label="Clear entry"` to describe what the button does.
Fixes #671
> Text inputs clear input accessibility issue fixes

- CHANGELOG.md
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/icons/icon-map.tsx
- stencil-workspace/src/components/modus-message/modus-message.e2e.ts
- stencil-workspace/src/components/modus-message/modus-message.tsx
- stencil-workspace/src/components/modus-message/readme.md
- stencil-workspace/src/components/modus-spinner/modus-spinner.scss
- stencil-workspace/storybook/stories/components/modus-message/modus-message-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-message/modus-message.stories.tsx
Added an Icon Map to allow icon names to be passed into components as props. Added a usage to the Modus Message component. 
This map will still need to be added to applicable components.
References #587
Manually and e2e
> Add Icon Map for dynamic icons (with usage in Message)

- .github/workflows/security-scan.yaml
- .github/workflows/super-linter.yml
Add GitHub's Super Linter Action to run on each PR. This checks using linters for most file-types and is very helpful in catching issues with files we don't already lint.
REF: https://github.com/github/super-linter
We already use this on most other Modus projects and found it very helpful. We can always disable linting for a particular type if it becomes annoying. I usually disable Markdown and Editorconfig linting as they can be very strict and not too helpful.
This PR also optimizes the CodeQL scan by removing the unused Autobuild step (this is only needed for compiled languages).
> Add GitHub's Super Linter Action

- stencil-workspace/.eslintrc.js
Adding this to the top of the `.eslintrc.js` file fixes a linting issue with ESLint itself:
```js
// eslint-disable-next-line no-undef
```
> Fix Eslint issue with `.eslintrc.js`

- .gitignore
- CONTRIBUTING.md
- README.md
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
I've updated the `README.md` to be consumer-focused. Anything that had to do with contributing is moved over to the `CONTRIBUTING.md` doc. 
I've added a script to copy the markdown files that we want included in the package.
Fixes #551
I installed this package manually to confirm that the `README.md` and `SUPPORT.md` exist
> Focus README on lib consumers

- CHANGELOG.md
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-data-table/modus-data-table.scss
- stencil-workspace/src/components/modus-data-table/modus-data-table.spec.ts
- stencil-workspace/src/components/modus-data-table/modus-data-table.utilities.ts
This fixes the issue where the column props were not converting the column `id`s. This makes it so we no longer need to use the string literal for the `data` property fields
Fixes #741
Manually, and unit tested.
> Fix Data Table ID setting bug

- CHANGELOG.md
- stencil-workspace/storybook/.storybook/main.js
- stencil-workspace/storybook/.storybook/preview.js
- stencil-workspace/storybook/package-lock.json
- stencil-workspace/storybook/package.json
- stencil-workspace/storybook/public/storybook-styles.css
Added a theme toggler using a [addon](https://storybook.js.org/addons/storybook-dark-mode) that uses local storage to retain the theme selection and also checks for user preference.
Also added some styles in the storybook for dark mode.
Fixes #787 
> Add Theme toggler for storybook

- .github/workflows/super-linter.yml
We shouldn't lint CSS with Super Linter because it uses a preset which is incompatible with out library. HTML should only be linted if we add a `.htmlhintrc` to the root (maybe we'll do this in the future).
This PR removes linting for those to avoid linting issues.
This is a dev-only change so no need to mention in CHANGELOG.
> Don't lint CSS and HTML with super-linter GitHub Action

- stencil-workspace/storybook/public/404/index.html
- stencil-workspace/storybook/public/staticwebapp.config.json
Fixes: #288
This is to avoid the Microsoft Azure branding on 404 page... and adds a link if users need to report a broken link from somewhere.
This PR also addresses some minor HTTP security header issues:
https://securityheaders.com/?q=https%3A%2F%2Fmodus-web-components.trimble.com%2F&hide=on&followRedirects=on
**With this merged the site will score A+**:
https://securityheaders.com/?q=https%3A%2F%2Ficy-ground-0374a1310-833.centralus.1.azurestaticapps.net%2F&hide=on&followRedirects=on
With Azure Deploy Preview
> Adds  a simple 404 page

- .gitignore
- react-workspace/README.md
- react-workspace/package.json
- stencil-workspace/README.md
- stencil-workspace/package.json
These are largely the same as the root's README for now, but they can diverge in the future.
Note: The change for the URL on the root's README was to fix a markdown linting issue.
Rationale: Without angle brackets, the URL isn't converted into a link in many markdown parsers.
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md034---bare-url-used
> Create separate README files for each output

- stencil-workspace/.stylelintrc.json
- stencil-workspace/src/components/modus-button/modus-button.vars.scss
- stencil-workspace/src/components/modus-content-tree/modus-tree-view-item.vars.scss
- stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss
- stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.scss
- stencil-workspace/src/global/themes.scss
- stencil-workspace/src/index.html
Note:
CSS variables defined inside component selectors ex: `modus-checkbox { --modus-checkbox-bg: white; }` won't work if the component is nested inside another component, ex: checkbox in a content tree item
As a workaround, we have added all the checkbox specific variables at the root. 
discussed with @coliff and decided to go this way, for now, @ryan-henness-trimble if you have any ideas do let us know.
Fixes #800 
> Dark mode for Content tree and Chip

- CHANGELOG.md
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
- stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
- stencil-workspace/src/components/modus-chip/modus-chip.tsx
- stencil-workspace/src/components/modus-number-input/modus-number-input.tsx
- stencil-workspace/src/components/modus-select/modus-select.tsx
- stencil-workspace/src/components/modus-slider/modus-slider.tsx
- stencil-workspace/src/components/modus-switch/modus-switch.tsx
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
These values were not getting set explicitly so only the attribute would get set in the DOM, which did not include the `=""`.
Fixes #569 
Manually in the dev env and Storybook
> Explicitly set aria disabled values

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- .github/workflows/super-linter.yml
- .markdownlint.json
- .prettierrc.json
- stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx
The `.prettierrc` config was not setup to match the formatting of the stencil-workspace directory. This PR removes the `printWidth` rule and runs Prettier on the folder. The Markdownlint config is added so any future PRs are linted.
> Formatting with Prettier

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-accordion/modus-accordion.tsx
- stencil-workspace/src/components/modus-alert/modus-alert.tsx
- stencil-workspace/src/components/modus-badge/modus-badge.tsx
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
- stencil-workspace/src/components/modus-button/modus-button.tsx
- stencil-workspace/src/components/modus-card/modus-card.tsx
- stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
- stencil-workspace/src/components/modus-chip/modus-chip.tsx
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
- stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx
- stencil-workspace/src/components/modus-message/modus-message.tsx
- stencil-workspace/src/components/modus-modal/modus-modal.tsx
- stencil-workspace/src/components/modus-number-input/modus-number-input.tsx
- stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
- stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
- stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
- stencil-workspace/src/components/modus-select/modus-select.tsx
- stencil-workspace/src/components/modus-slider/modus-slider.tsx
- stencil-workspace/src/components/modus-switch/modus-switch.tsx
- stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Making ariaLabel nullabe.
Was using this npm package on my angular project and was confronted with an error when compiling:
```
Error: node_modules/@trimble-oss/modus-web-components/dist/types/components.d.ts:1115:15 - error TS2320:
Interface 'HTMLModusTooltipElement' cannot simultaneously extend types 'ModusTooltip' and 'HTMLStencilElement'.
Named property 'ariaLabel' of types 'ModusTooltip' and 'HTMLStencilElement' are not identical.
1115     interface HTMLModusTooltipElement extends Components.ModusTooltip, HTMLStencilElement {
```
`HTMLStencilElement` extends `HTMLElement` that extends `Element` that extends `ARIAMixin` that has the property:
```
interface ARIAMixin {
...
ariaLabel: string | null;
...
}
```
Fixes # (issue) Didn't create issue
ran `npm run test` and all tests passed
> Making ariaLabel nullable

- stencil-workspace/storybook/public/storybook-styles.css
H1, H2 headings underline color is not so bright in dark mode, fixed it.
> Fix headings underline color in dark mode

- stencil-workspace/storybook/package-lock.json
- stencil-workspace/storybook/package.json
This acts as a warning about Node v18 compatibility in light of #898
`npm install` works as normal and expected with node v16.18.1
> Add engines to `package.json`

- stencil-workspace/storybook/.storybook/main.js
- stencil-workspace/storybook/package-lock.json
- stencil-workspace/storybook/package.json
- stencil-workspace/storybook/postcss.config.js
This fixes the deprecated PostCSS plugins issue in Storybook. I followed the steps in the Migration guide:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins
Fixes: https://github.com/trimble-oss/modus-web-components/issues/333
Build completes locally with no errors
> Fix Default PostCSS plugins are deprecated in Storybook

- stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts
- stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
When clicking on the chevrons for the `modus-pagination` it wouldn't emit a `pageChange` event.
This feature has been added in this PR.
> Fixes # (issue)
No issue was created for this.
Added e2e tests for the new feature.
Ran `npm run test` in `stencil-workplace` and all tests passed.
Did some manual testing in the `stencil-workplace/src/index.html` with the following snippet:
```html
<modus-pagination active-page="1" max-page="10" min-page="1"></modus-pagination>
<script>
const pagination = document.querySelector('modus-pagination');
pagination.addEventListener('pageChange', event => { 
console.log('pageChange', …
```
> bubbling events after chevron interactions

- .github/workflows/sonar-scan.yml
Fixes this issue reported in SonarQube Web UI:
> Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.
This matches the format we have for Modus Style guide site which doesn't have this error. https://github.com/trimble-oss/website-modus.trimble.com/blob/main/.github/workflows/sonar-scan.yml
> Fix Shallow clone SonarQube scan GitHub Action

- CHANGELOG.md
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
- stencil-workspace/src/components/modus-navbar/apps-menu/readme.md
- stencil-workspace/src/components/modus-navbar/main-menu/modus-navbar-main-menu.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
- stencil-workspace/src/components/modus-navbar/modus-navbar.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
- stencil-workspace/src/components/modus-navbar/readme.md
- stencil-workspace/src/index.html
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Center the navbar buttons and output some new events to let applications know when the menus are opening, and when apps/links are opened
Fixes #985 
Fixes #986 
E2e and manually tested
> Center Navbar buttons vertically, add open events

- CHANGELOG.md
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.scss
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
- stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
There's a bug where the breadcrumbs push to the route when there was no route specified for that breadcrumb.
Fixes #1015 
Manually tested
> Remove unused href from Breadcrumb anchor

- CHANGELOG.md
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
- stencil-workspace/src/components/modus-modal/modus-modal.vars.scss
This PR updates the default modus-modal backdrop color to be consistent with the default theme color. For existing users of modus-web-components they will now get consistent default UX when upgrading to the latest version.
Prior to this fix, when upgrading to the latest version the default backdrop color for the modus-modal was completely opaque.
Fixes #1061 
- Tested manually by using the component inside the test index.html page with and without the global themes applied in stencil.config.json
- Added an e2e test to ensure that the styles are being applied correctly from the theme however I was unable to write an e2e test that covers the styles when themes are not applied. There is still a gap there for "default" component behavior.
> Issue 1061: Updated modus-modal default backdrop color

- CHANGELOG.md
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-toast/modus-toast.scss
- stencil-workspace/src/components/modus-toast/modus-toast.spec.ts
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
Text overflowing the Toast was wrapping to a new line and displaying outside of the Toast
Fixes #1094
> Add an ellipsis to text overflowing Modus Toast

- CHANGELOG.md
- stencil-workspace/src/components/modus-switch/modus-switch.scss
Fixes: #1099
Locally with Edge v110
> Reduce Switch input animation from .2s to .1s

- stencil-workspace/storybook/.storybook/main.js
- stencil-workspace/storybook/package-lock.json
- stencil-workspace/storybook/package.json
Fixes: #1189
storybookjs/addon-postcss is deprecated - we need to migrate to storybookjs/addon-styling
This is required for the update to Storybook v7.x
> Migrate from deprecated addon-postcss to addon-styling Storybook add-on

- angular-workspace/LICENSE
Modus Angular components npm package is missing a LICENSE. This PR will fix it when it's next published https://npmjs.com/package/@trimble-oss/modus-angular-components?activeTab=code
Fixes: #1154
> Add MIT LICENSE to Angular Components (for npm package)

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-switch/modus-switch.scss
- stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
When we release the new [modus-data-table](https://deploy-preview-1231--modus-webcomponents.netlify.app/?path=/story/components-data-table--default), we must warn users not to use [modus-table](https://deploy-preview-1231--modus-webcomponents.netlify.app/?path=/story/components-table--default)(renamed because it used to be `modus-data-table`) component and it will be deprecated soon.
Note: the branch will not merge to `main` branch directly until data table is available.
Fixes #693 
> Add a deprecation warning to the Modus Table

- CONTRIBUTING.md
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-data-table/modus-data-table.scss
Set the deprecated table's header min height instead of height.
Also removed the section about updating the CHANGELOG in the CONTRIBUTING doc
Fixes #1263 
Manually through the index.html
> (Deprecated Data Table) Fix header min-height

- stencil-workspace/src/components/modus-card/modus-card.scss
Fixes: #1299
Modus Card component has border when showCardBorder property is set on false. 
Locally with Edge v113
> Fix for border color on modus-card

- stencil-workspace/storybook/.storybook/preview-head.html
Material Icons are not used or needed
> Remove Material Icons from Storybook preview window

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.scss
- stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.spec.ts
- stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
- stencil-workspace/src/components/modus-progress-bar/readme.md
- stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx
Note: The small variant on the site right now was referred to compact in some places.
There is now both a small (8px) and compact variant (4px). 
PREVIEW: https://icy-ground-0374a1310-1296.centralus.1.azurestaticapps.net/?path=/docs/components-progress-bar--default
> Add Compact Progress Bar variant (4px height)

- stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
There is no need to load Material Icons now.
> Remove mention about needing Material icons on getting-started

- .prettierrc.json
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
Fixes:
- The default prettier config sets: "printWidth": 80, by default which is too narrow. Suggest we change it to 125.
- Currently the npm run prettier command in storybook dir only runs on storybook/stories/ - we should also run it on the src/ dir 
- We can update Prettier dev dep from v2.8.7 to v2.8.8 too
> Update Prettier Config ("printWidth": 125)

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- react-workspace/src/components/stencil-generated/react-component-lib/createComponent.tsx
- react-workspace/src/components/stencil-generated/react-component-lib/createOverlayComponent.tsx
- react-workspace/src/components/stencil-generated/react-component-lib/utils/case.ts
- react-workspace/src/components/stencil-generated/react-component-lib/utils/index.tsx
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/icons/icon.spec.tsx
- stencil-workspace/src/components/modus-data-table/readme.md
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.e2e.ts
- stencil-workspace/src/components/modus-radio-group/modus-radio-group.e2e.ts
- stencil-workspace/stencil.config.ts
- Walked through Stencil's upgrade guide: https://stenciljs.com/docs/v2/introduction/upgrading-to-stencil-three#add-customelementsexportbehavior-to-control-export-behavior
- Fixed an issue with a `modus-radio-group.e2e.ts` import path
- Fixed an issue with an unused variable in `modus-date-picker.e2e.ts`
- Fixed `icon.spec.ts`. There was an unneeded `Component` import that was causing rollup errors
**I noted my thought process throughout the upgrade, please open and check the detailed notes below**:
<details>
<summary>Upgrade Guide Notes</summary>
Manually set the `sourceMap` config to `false` 
Source maps should not be included in our production builds as they are representations of the original code. Including them would increase bundle size and impact performance
Manually set …
> Upgrade to Stencil 3.0

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Added a couple of optional fields to help with Modus adoption tracking.
template:
GitHub Issue templates
> Added a few optional fields to the GitHub issue templates

- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Make `category` and `showCategory` properties optional as they are not really required.
Storybook example code blocks
> Make `category` and `showCategory` optional for Modus Navbar's apps menu

- .github/workflows/azure-static-web-apps-deploy.yml
We should consider skipping the Azure Static Web App step when there are missing secrets. PRs from a forked branch are not working since they don't have access to the secrets, which is blocking merging
We can depend on the Netlify deployment for checking the preview
> Skip Azure Static Web App deployment on missing secrets

- .github/workflows/azure-static-web-apps-deploy.yml
There's limited information on `skip_deploy_on_missing_secrets` in the Microsoft docs. Dapr has an example [here](https://docs.dapr.io/contributing/docs-contrib/maintainer-guide/) that shows the parameter actually goes in the `with` section
> Fix deployment skip parameter

- stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Adding the tooltip properties to the modus-tooltip stories in Storybook. Adding a button inside the tooltip to be able to see the tooltip in Storybook.
References #1276
Tested locally.
> add tooltip to canvas section in storybook

- .github/workflows/azure-static-web-apps-deploy.yml
Prevent Azure SWA Deploy Preview being deployed when changes are made to files where it wouldn't affect the Storybook site.
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions extension was installed and offers real-time validation of GitHub Actions and reported no issues.
> Prevent Azure SWA Deploy Preview being deployed when not needed

- stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
- stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
- stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
- stencil-workspace/src/components/modus-checkbox/modus-checkbox.vars.scss
- stencil-workspace/src/global/themes.scss
Modus checkbox focus state corrections 
- Focused exclusively on the checkbox and ignoring the label.
- Focus state colors (for light and dark) are updated, taken from the Modus Trimble style guide.
References [#1393](https://github.com/trimble-oss/modus-web-components/issues/1393)
> Modus checkbox focus state corrections - focused exclusively on the checkbox and ignoring the label

- stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Add the missing `disabled` in controls tab in Storybook page for Modus Tooltip
Preview: 
Note: Might fix https://github.com/trimble-oss/modus-web-components/issues/1303
> Update Modus Tooltip Storybook page to add `disabled` control

- stencil-workspace/src/interfaces.d.ts
Duplicate interface export is causing the below build error in Angular components,
Error: [node_modules/@trimble-oss/modus-web-components/dist/types/interfaces.d.ts:4:10](mailto:node_modules/@trimble-oss/modus-web-components/dist/types/interfaces.d.ts:4:10) - error TS2300: Duplicate identifier 'ModusNavbarProfileMenuLink'.
4 export { ModusNavbarProfileMenuLink } from './components/modus-navbar/profile-menu/modus-navbar-profile-menu';
Remove the duplicate export.
References #1427
> Remove duplicate `ModusNavbarProfileMenuLink` export

- stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts
- stencil-workspace/src/components/modus-alert/modus-alert.scss
- stencil-workspace/src/components/modus-alert/modus-alert.spec.ts
- stencil-workspace/src/components/modus-alert/modus-alert.tsx
- stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
- stencil-workspace/src/global/themes.scss
- stencil-workspace/storybook/public/storybook-styles.css
- stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-alert/modus-alert.stories.tsx
- stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
Fixes #1500 
It's essential to offer users the option to include custom message content, such as adding a hyperlink to the message, as shown in Modus Bootstrap and Modus React Bootstrap.
Preview: https://icy-ground-0374a1310-1491.centralus.1.azurestaticapps.net/?path=/story/components-alert--with-link
No issue is attached.
> Added support for slot in Modus Alert

- angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json
- angular-workspace/projects/trimble-oss/modus-angular-components/package.json
- react-workspace/react-17/package-lock.json
- react-workspace/react-17/package.json
- react-workspace/react-18/package-lock.json
- react-workspace/react-18/package.json
- Version bumps for MWC from `"0.1.45"` to `"0.1.46"`
- React Component Library now has suffix react17 or react18 (instead of just 17 or 18)
> Release v0146 for React and Angular

- .github/workflows/publish-angular.yml
- package.json
This PR
- GitHub Action was failing (see logs: https://github.com/trimble-oss/modus-web-components/actions/workflows/publish-angular.yml) because we need to change directory and run npm install
- Modifies the script in the root `package.json` to update version numbers of MWC in all 5 packages.
> Fix for npm publish steps GH Action

- stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
- stencil-workspace/src/components/modus-modal/modus-modal.tsx
- stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
References #1591 
Added Actions for `primaryButtonClicked` and `secodnaryButtonClicked` in Storybook canvas page. We can click on the buttons to see if the actions are showing up.
https://deploy-preview-1592--modus-webcomponents.netlify.app/?path=/story/components-modal--default&args=primaryButtonDisabled:true;secondaryButtonDisabled:true
> Fix incorrect triggering of disabled button events in Modal

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-card/modus-card.e2e.ts
- stencil-workspace/src/components/modus-card/modus-card.tsx
- stencil-workspace/src/components/modus-card/readme.md
- stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
Since we already have a CSS variable to customize the background colour for Cards, we removed the `backgroundColor` prop from Modus Cards component as it unnecessarily complicates the code.
Also enabled the controls tab for testing the properties on Storybook. 
References #1166 
Please navigate to the Modus Cards page on Storybook. Once there, you can adjust the values of various properties using the controls tab. Please note that the background colour property is no longer available.
> Modus Cards - Remove `backgroundColor` prop and encourage using CSS variable `--modus-card-bg`

- stencil-workspace/src/components/modus-content-tree/modus-content-tree-drag-item.tsx
- stencil-workspace/src/components/modus-content-tree/modus-content-tree.constants.tsx
- stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
- stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.scss
- stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
- stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
- Fixed border line for dragging content 
- Fixed dragging content initial positioning 
- Fixed and add missing controls for Storybook
References #1414 
Goto Modus Content tree - Actions bar page on the storybook and click on the drag action button to enable dragging on the tree items and click on expand action button to expand all the items. 
Now try dragging a tree item and dropping it in another location inside the tree.
> Fix Modus Content Tree UI issues with drag and drop

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/icons/IconMap.tsx
- stencil-workspace/src/components/icons/icon-caret-down.tsx
- stencil-workspace/src/components/modus-button/modus-button.e2e.ts
- stencil-workspace/src/components/modus-button/modus-button.scss
- stencil-workspace/src/components/modus-button/modus-button.spec.ts
- stencil-workspace/src/components/modus-button/modus-button.tsx
- stencil-workspace/src/components/modus-button/modus-button.vars.scss
- stencil-workspace/src/components/modus-button/readme.md
- stencil-workspace/src/global/modus-light-theme.scss
- stencil-workspace/src/global/themes.scss
- stencil-workspace/src/index.html
- stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
- stencil-workspace/storybook/stories/components/modus-spinner/modus-spinner-storybook-docs.mdx
Added support for Icon with Text Buttons, Icon-only Buttons, and Buttons with Caret Icon.
Note: The only breaking change is `--modus-btn-outline-dark-color:` replaced by `--modus-btn-outline-secondary-color:` to make it in sync with Figma.
Fixes #806,  #1539, #274, #1126
Buttons:
https://icy-ground-0374a1310-1590.centralus.1.azurestaticapps.net/?path=/docs/components-button--default
Dropdown (added caret icon):
https://icy-ground-0374a1310-1590.centralus.1.azurestaticapps.net/?path=/docs/components-dropdown--default
Spinner (removed loading button as part of Animations Issue #1126 ):
https://icy-ground-0374a1310-1590.centralus.1.azurestaticapps.net/?path=/docs/components-spinner--default
> Add support for Icon(s) in Modus Button component

- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/modus-table.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
- stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx
- stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
If the expanded column functionality and scroll are set to true, the first column will be sticking to the left.
References #1593
> Added functionality to make first column sticky

- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
Fixes #1606 
Go to Date Picker page on Storybook and should not see any warning message.
> Modus Date Picker Storybook page - Remove "under construction" warning message

- stencil-workspace/src/global/themes.scss
Fixes #1435, #1432, #1436
Breaking change: Removed unused Gray 11 
Check background colour and disabled font colour for Content Tree, List, Dropdown and wherever Gray 10 and Trimble Gray are supposed to be present.
> Fixed the incorrect color code for Gray 10 and Trimble Gray

- stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
- stencil-workspace/src/components/modus-number-input/modus-number-input.tsx
- stencil-workspace/src/components/modus-select/modus-select.tsx
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.tsx
- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
- stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
- stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
- stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker.stories.tsx
The `aria-` attributes moved from the `div` to the `input` element. 
Note: 
Did not fix the `aria-placeholder` on the Number Input Component as it is not clear whether it is okay to remove the attribute.
References #1044
> Fix Accessibility Errors on the User Input Components

- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components/modus-select/modus-select.e2e.ts
- stencil-workspace/src/components/modus-select/modus-select.tsx
- stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
This fixes an issue where the setter and emitter for the current value was using the object's display property rather than the object itself.
Closes #1643
Manually installing into our project, and e2e tests.
> Select Component: Set and emit value by object ref instead of display prop

- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Replace the Navbar's Apps menu apps' `<div>` elements with `<a>` elements for better accessibility and semantics
Fix navbar doc snippets
Closes #1665 
Manually
> Use `<a>` for Navbar apps menu apps. Fix Navbar doc snippets

- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Fixes #1669
Preview:
Press Add icon in https://icy-ground-0374a1310-1670.centralus.1.azurestaticapps.net/?path=/docs/components-navbar--default and notice the padding for the dropdown 
Press Add icon in https://icy-ground-0374a1310-1670.centralus.1.azurestaticapps.net/?path=/docs/components-navbar--default
> Fix the default padding for dropdown menus in Modus Navbar component

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
- react-workspace/react-17/src/components/stencil-generated/index.ts
- react-workspace/react-18/src/components/stencil-generated/index.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-table/modus-table.e2e.ts
- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/modus-table.spec.tsx
- stencil-workspace/src/components/modus-table/modus-table.tsx
- stencil-workspace/src/components/modus-table/parts/fillerColumn/modus-table-filler-column.scss
- stencil-workspace/src/components/modus-table/parts/fillerColumn/modus-table-filler-column.tsx
- stencil-workspace/src/components/modus-table/parts/fillerColumn/readme.md
- stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
- stencil-workspace/src/components/modus-table/readme.md
When there are not too many columns in the table to occupy the full width that is set, we show a filler column inside the table after the last column.
References #1529
> Added a space filler column to Modus Table

- angular-workspace/test-ng14/angular.json
- angular-workspace/test-ng14/package.json
- angular-workspace/test-ng15/angular.json
- angular-workspace/test-ng15/package-lock.json
- angular-workspace/test-ng15/package.json
- react-workspace/test-react-v17/package-lock.json
- react-workspace/test-react-v17/package.json
- react-workspace/test-react-v17/src/examples/ModusTableExamples.tsx
- react-workspace/test-react-v18/package-lock.json
- react-workspace/test-react-v18/package.json
- react-workspace/test-react-v18/src/examples/ModusTableExamples.tsx
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-table/modus-table.tsx
When using an alias for imports, the file [`stencil-workspace\src\components.d.ts`](https://github.com/trimble-oss/modus-web-components/pull/1720/files#diff-9882712136553263a8d8cc3feb8559f936509913478623fa7a4bd2cdff060677) contains the alias instead of the original import name, which causes the Angular applications to throw errors.
References #1719 
Make sure the build passes, and the storybook page for Modus Table component works fine.
> Remove alias for imports to avoid errors on `components.d.ts` file

- stencil-workspace/src/components/modus-button/modus-button.vars.scss
- stencil-workspace/src/components/modus-toast/modus-toast.vars.scss
The issue was when the [theme css](./node_modules/@trimble-oss/modus-web-components/dist/modus-web-components/modus-web-components.css) is not referenced because of the missing fallback colours, some buttons did not have a proper background color, like secondary and danger buttons. The fix was to remove the usage of `$theme-colors` variable and replaced it with the color codes.
References #1694 
Not sure how to test this on the storybook because it has a reference to the theme file. Below shows the video taken from a localhost by commenting out the theme file in `index.html`,
> Fix the missing fallback colors for button component

- stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.state.tsx
Add left padding to month/day values less than 10 in order to comply with ISO 8601 format.
References #1753
- [ X] Bug fix (non-breaking change which fixes an issue)
console inspection and npm run test
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] My changes generate no new warnings
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules
- [ X] I have checked my code and corrected any misspellings
> Fix date picker setDate iso8601 compliance

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-alert/modus-alert.scss
- stencil-workspace/src/components/modus-table/modus-table.e2e.ts
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-link-element.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
- stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
- stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
- stencil-workspace/src/components/modus-table/utilities/table-cell-navigation.utility.tsx
- stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
- stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
References #1811 
https://deploy-preview-1812--modus-webcomponents.netlify.app/?path=/story/components-table--hyperlink
Navigate to any of the row cell with hyperlink using the Tab key and focus the hyperlink inside the cell and press Enter key to trigger cell link click event visible under Actions tab
> Fix the non-accessible hyperlink cell content in Modus Table

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/icons/icon-shield.tsx
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.e2e.ts
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
- stencil-workspace/src/components/modus-side-navigation/readme.md
- stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
1. Added a configuration to stop the collapsing of the side navigation panel when clicked outside.
2. Enables controls for Modus Side Navigation component examples on the canvas tab
References #1849 
Go to [the storybook preview for Modus Side Navigation component](https://deploy-preview-1854--modus-webcomponents.netlify.app/?path=/story/components-side-navigation--default&args=collapseOnClickOutside:false) and change the control `collapseOnClickOutside` to false to stop the panel from collapsing automatically when clicked outside.
> Modus Side Navigation - Added `collapseOnClickOutside` configuration

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.spec.tsx
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.spec.ts
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
- stencil-workspace/src/components/modus-tooltip/readme.md
- stencil-workspace/src/index.html
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
Integrated [PopperJs](https://popper.js.org/docs/v2/tutorial/) for the Modus tooltip component.
References #1691 
To see the tooltip working, go to the Storybook preview page for the Modus tooltip component or any other component that is using Modus Tooltips like Modus Navbar (on the Add button), Modus Side Navigation items when collapsed, Modus Table header sort icons. On the Tooltip Storybook page, use the controls to set the `disabled` to `false` or clear the tooltip text to see no tooltip appearing.
> Added PopperJs for Modus Tooltips

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
- react-workspace/react-17/src/components/stencil-generated/index.ts
- react-workspace/react-18/src/components/stencil-generated/index.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-table/models/table-context.model.ts
- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/modus-table.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
- stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
- stencil-workspace/src/components/modus-table/parts/modus-table-footer.tsx
- stencil-workspace/src/components/modus-table/parts/modus-table-header.tsx
- stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
- stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions-cell.tsx
- stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.scss
- stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
- stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/readme.md
- stencil-workspace/src/components/modus-table/readme.md
- stencil-workspace/src/index.html
- Added custom row actions to the Modus Table configuration with keyboard navigation.
- Up to four icons (including expandable and overflow icons) can be displayed for unlimited row actions.
- Enabled Keyboard navigation on Modus List component
- Refactored code to allow all child components to obtain details from a single context object.
References https://github.com/trimble-oss/modus-web-components/issues/1729
Storybook page
Go to [preview](https://deploy-preview-1857--modus-webcomponents.netlify.app/?path=/story/components-table--row-actions) and edit the rowActions control to add/remove row actions. Users should be able to use keyboard to select the row actions and press escape key to escape the overflow menu dropdown.
> Modus Table - Add row actions

- angular-workspace/test-ng14/src/examples/modus-navbar-examples/modus-navbar-examples.component.ts
- angular-workspace/test-ng15/src/examples/modus-navbar-examples/modus-navbar-examples.component.ts
- stencil-workspace/src/components/modus-navbar/modus-navbar.scss
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
- Use a valid URL which doesn't load an image: https://avatar.example.com/broken-image-link.png
- Set `max-height:32px` and `max-width:32px` to prevent failed image to appear much larger.
- Add `display: flex` to set it to display correctly.
Locally, works every time.
> Fix for Failed Avatar navbar example is not using a valid URL

- stencil-workspace/src/components/modus-date-input/modus-date-input.scss
- stencil-workspace/src/components/modus-date-input/modus-date-input.vars.scss
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.vars.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.vars.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.vars.scss
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.vars.scss
- stencil-workspace/src/global/themes.scss
- stencil-workspace/src/sample.html
Set background color for readonly text input. This works good in all modern browsers, but it does use the :has selector which is relatively new. (REF: https://caniuse.com/css-has).
Locally with Edge v119. Tested in light and dark mode.
> Set background color for readonly inputs

- stencil-workspace/src/components/modus-table/modus-table.tsx
The error is happening in storybook when opening the Checkbox Row Selection story from the Table component
References #
> bug undefined tableCore

- stencil-workspace/src/components/modus-list-item/modus-list-item.scss
Default list-item font-size was 16px but should be 14px. Large size remains the same (16px).
References #
> Fix for font-size for list item

- angular-workspace/test-ng14/src/examples/modus-card-examples/modus-card-examples.component.ts
- angular-workspace/test-ng15/src/examples/modus-card-examples/modus-card-examples.component.ts
- react-workspace/test-react-v17/src/examples/ModusCardExamples.tsx
- react-workspace/test-react-v18/src/examples/ModusCardExamples.tsx
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/sample.html
- stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
Setting `id="card-title"` and `id="card-subtitle"`  on all cards would result in invalid HTML (id's must be unique). These IDs serve no purpose and make the examples appear noisy.
Locally with Edge v120 on Windows 11 Pro.
> Docs: Remove problematic id="card-title" and id="card-subtitle" from card examples

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-list-item/modus-list-item.e2e.ts
- stencil-workspace/src/components/modus-list-item/modus-list-item.scss
- stencil-workspace/src/components/modus-list-item/modus-list-item.spec.ts
- stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
- stencil-workspace/src/components/modus-list-item/readme.md
- stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
Added support for sub-text in the modus list item component
Added support for sub-text in the modus list item component
References #1957 
We have to provide a value for the sub-text property and that value should be rendered below the slot in the modus list item.
> List: Add support for sub-text in list item

- .github/workflows/issue-thanks.yml
- angular-workspace/ng16/package-lock.json
- angular-workspace/test-ng14/package-lock.json
- angular-workspace/test-ng14/package.json
- angular-workspace/test-ng15/package-lock.json
- angular-workspace/test-ng15/package.json
- angular-workspace/test-web-components/package-lock.json
- react-workspace/test-react-v17/package-lock.json
- react-workspace/test-react-v17/package.json
- react-workspace/test-react-v18/package-lock.json
- react-workspace/test-react-v18/package.json
- react-workspace/test-web-components/package-lock.json
Note: This pull request resolved a Dependabot alert on follow-redirects.
Fixes many of these in a single PR to cut down on multiple Dependabot PRs being merged:
> Bump follow-redirects to 1.15.4

- .github/workflows/azure-static-web-apps-deploy.yml
- .vscode/settings.json
- README.md
- stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
- stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
- stencil-workspace/storybook/stories/introduction/contributing.stories.mdx
- stencil-workspace/storybook/stories/introduction/welcome.stories.mdx
This changes the deploy to Azure GitHub Action so that it only runs when a new release is published - so therefore https://modus-web-components.trimble.com/ will always only show the code from the latest release.
https://moduswebcomponents.netlify.app/ will always show latest dev changes.
+ various docs fixes
+ markdown linting fix for root README.md
> Only deploy to modus-web-components.trimble.com on release

- stencil-workspace/src/components/modus-navbar/product-logo/modus-navbar-product-logo.tsx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Added tab index to the e-builder log so it can now be tabbed to. Also added a keydown function so that when the enter key is hit on the logo, it will copy the functionality of clicking it. 
References [#2040](https://github.com/trimble-oss/modus-web-components/issues/2040)
> Navbar: add tab index to logo and trigger productLogoClick with keyboard

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/src/components/modus-text-input/readme.md
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Add support for email, url, tel and search inputs
Fixes: #524
Preview: https://deploy-preview-2054--moduswebcomponents.netlify.app/?path=/story/user-inputs-text-input--default
Locally with Storybook (Edge v120).
> Text-Input: Add support for email, url, tel and search inputs

- stencil-workspace/src/components/modus-badge/modus-badge.tsx
The recently introduced BadgeProperties type, which is used to share props between the standalone Badge and the Table's Badge Cell, defined the `ariaLabel` property as optional while the Badge component ultimately extends ARIAMixin which does not define it as optional.  This mismatch caused the conflict that prevented the build.
References #2004
- Ran `npm run build` within `test-web-components` folder (angular app)
- Witness error
- Applied fix
- Ran `npm run build` within `stencil-workspace` 
- Copied `dist` and `loader` folders to overwrite those in `angular-workspace\test-web-components\node_modules\@trimble-oss\modus-web-components\`
- Ran `npm run build` within `test-web-components` folder (angular app)
- Observed passing build
> Badge: Fix issue breaking angular builds

- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
This means that user can press <kbd>Escape</kbd> key to clear the input.
References #2044 
Locally with Edge v120 on Windows 11.
Preview:
https://deploy-preview-2061--moduswebcomponents.netlify.app/?path=/story/user-inputs-autocomplete--default
Type in something and then press <kbd>Escape</kbd> key to clear the input.
> Autocomplete: Use input `type="search"`

- stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
Add `aria-label` to icon-only buttons on Storybook site.
References #2077
Locally with Edge v121
> Docs: Add aria-label to icon-only buttons

- stencil-workspace/src/components/modus-alert/modus-alert.scss
- stencil-workspace/src/components/modus-badge/modus-badge.scss
- stencil-workspace/src/components/modus-button/modus-button.scss
- stencil-workspace/src/components/modus-card/modus-card.e2e.ts
- stencil-workspace/src/components/modus-card/modus-card.scss
- stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss
- stencil-workspace/src/components/modus-list/modus-list.scss
- stencil-workspace/src/components/modus-message/modus-message.scss
- stencil-workspace/src/components/modus-modal/modus-modal.scss
- stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss
- stencil-workspace/src/components/modus-pagination/modus-pagination.scss
- stencil-workspace/src/components/modus-tabs/modus-tabs.scss
- stencil-workspace/src/components/modus-toast/modus-toast.scss
- stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
- stencil-workspace/src/global/modus-variables.scss
- stencil-workspace/src/global/shared-mixins.scss
- stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
- Change border radius from 2px to 4px for components
- Change Border-width for File Upload Dropzone from 1px to 2px
- Remove `aria-label="Card"` from card example on docs (not needed)
Locally with Edge v120 on Windows 11
> Change border radius from 2px to 4px for components

- stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
Changes that box wrapper from `width: 100px` to `min-width: 100px` and alpha-sorts the CSS (as we do that everywhere else).
References #2103
Locally with Edge v121 on Windows 11.
PREVIEW: https://deploy-preview-2104--moduswebcomponents.netlify.app/?path=/story/components-icons--default&args=name:battery_charging_horizontal
> Fix storybook issue with icon names being cropped

- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
- stencil-workspace/src/components/modus-date-input/modus-date-input.scss
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.scss
- stencil-workspace/src/components/modus-select/modus-select.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Change Form inputs to have `border-radius: 4px` for form inputs:
- Autocomplete
- Text Input
- Date Input
- Number Input
Storybook with Edge v121 on Windows 11
> Form inputs: CSS change to `border-radius: 4px`

- stencil-workspace/src/components/modus-navbar/modus-navbar.scss
- stencil-workspace/src/components/modus-switch/modus-switch.scss
Added outline and border color to the profile menu icon when in a hover state.
References [#2088](https://github.com/trimble-oss/modus-web-components/issues/2088)
> Navbar: Add hover border/outline to profile menu icon

- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-link-element.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
Wrap the hyperlink in the modus-table when `wrapText` is enabled.
References #1998
> Table: Add support for wrapping hyperlink cells

- stencil-workspace/src/components/modus-table/modus-table.e2e.ts
- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header.tsx
Bold table column header text when sorting by column.
We received feedback from users that it is difficult to see what column is used for sorting. Bolding the header text would draw attention and make the sorted column stand out from the rest.
References #2097 
Added e2e test to validate
All unit and e2e tests passed when executing `npm run test`
Exploratory testing also performed in browser using modus-table component
> Table: Bold table header text on sort

- stencil-workspace/src/components/modus-select/modus-select.scss
- stencil-workspace/src/components/modus-select/modus-select.vars.scss
- stencil-workspace/src/global/themes.scss
Select: Use Custom Modus Icon
Fixes: #2125
This is a big improvement - improved padding and icon is less thick!
BEFORE:
AFTER:
PREVIEW: https://deploy-preview-2127--moduswebcomponents.netlify.app/?path=/docs/user-inputs-select--default
Firefox, Edge, Chrome
> Select: Use Custom Modus Icon

- stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
Navbar: Use `type="search"` on search input
Fixes: #2149
Locally with Edge v121
> Navbar: Use `type="search"` on search input

- stencil-workspace/src/components/modus-button/modus-button.scss
This PR changes icon-only buttons to be the same set height as width.
References #1626
Locally with Edge v121
Preview URL: https://deploy-preview-2148--moduswebcomponents.netlify.app/?path=/story/components-button--icon-only&args=size:medium
> Button: Fix icon-only button width inconsistency

- stencil-workspace/src/components/modus-dropdown/modus-dropdown.scss
- stencil-workspace/src/components/modus-list-item/modus-list-item.scss
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
I also made a small change to the Storybook Canvas demo to fix one of the two accessibility issues (by adding aria-label to the dropdown).
Partial fix for: #1195
Preview: https://deploy-preview-2164--moduswebcomponents.netlify.app/?path=/story/components-dropdown--default
Locally with Edge v121 on Windows 11 Pro
https://deploy-preview-2164--moduswebcomponents.netlify.app/?path=/story/components-dropdown--default
> Dropdown: Change border-radius to 4px

- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.spec.ts
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.spec.tsx
- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
REF: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role#:~:text=Note%3A%20Using%20the%20%3Cnav%3E%20element%20will%20automatically%20communicate%20a%20section%20has%20a%20role%20of%20navigation.%20Developers%20should%20always%20prefer%20using%20the%20correct%20semantic%20HTML%20element%20over%20using%20ARIA
Fixes: #2165
Locally with Edge v121 and NVDA for Windows
> Breadcrumb: Remove unnecessary `role="navigation"` from navs

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.scss
- stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
- stencil-workspace/src/components/modus-breadcrumb/readme.md
- stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
- Added a prop `underline`  for the underline to be displayed with the breadcrumbs.
References #
#2168 
https://deploy-preview-2196--moduswebcomponents.netlify.app/?path=/story/components-breadcrumb--default&args=underline:true
> Breadcrumbs: Add underline property

- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
- stencil-workspace/src/components/modus-accordion/modus-accordion.scss
- stencil-workspace/src/components/modus-accordion/modus-accordion.tsx
+ Use Modus Icons for Expand/Collapse
+ Improved horizontal padding (increased from 4px to 8px)
+ Add shadow
+ Add `border-radius: 4px`
References #
https://deploy-preview-2236--moduswebcomponents.netlify.app/?path=/story/components-accordion--default
> Accordion: Use Modus Icons for Expand/Collapse

- stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.scss
REF: https://modus-web-components.trimble.com/?path=/story/components-sentiment-scale--default&args=ariaLabel:was+this+page;disabled:true
Disabled sentiment scale was displaying as if it was enabled with hover state color change and pointer change. This PR removes the pointer events.
References #
> Sentiment Scale: Remove hover state for disabled state

- angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-button/modus-button.spec.ts
- stencil-workspace/src/components/modus-button/modus-button.tsx
- stencil-workspace/src/components/modus-button/readme.md
- stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
Add option to specify a button type. Defaults to `button`
References #
npm run test completes without issues
> Button: Add type option (`button`, `submit`, `reset`)

- stencil-workspace/src/components/modus-data-table/parts/modus-data-table-row-action-dropdown.tsx
Remove the border on the deprecated table's context menu dropdown
References #2229
Manually
> Data Table: Remove row action menu dropdown border

- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
- stencil-workspace/src/components/modus-accordion-item/readme.md
- stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion.stories.tsx
- Added a property `icon` to accordion which can accept any modus icon
- Added a test case to check icon property being set or not set.
Fixes: #2258
https://deploy-preview-2261--moduswebcomponents.netlify.app/?path=/story/components-accordion--default&args=icon:heart
> Accordion: Add icon property to accordion

- stencil-workspace/src/components/modus-button/modus-button.scss
Follow up fix for: #2244
- Locally: http://localhost:6006/?path=/story/components-button--default&args=ariaDisabled:true
- Deploy Preview: https://deploy-preview-2269--moduswebcomponents.netlify.app/?path=/story/components-button--default&args=ariaDisabled:true
> Button: Make `aria-disabled` buttons look disabled (CSS fix)

- stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
Fixes: #1195
https://deploy-preview-2279--moduswebcomponents.netlify.app/?path=/story/components-dropdown--default
> Dropdown: Remove unnecessary `role="listbox"`

- stencil-workspace/src/components/modus-table/modus-table.tsx
Updated how the sortFn is defaulted to alphanumeric to account for column being immutable.
References #2273
Ran locally to verify that sort behavior was unchanged and was still case insensitive.
> Table: Update how sortFn is defaulted to account for immutable column

- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
- stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
There are accessibility warnings on a few components.
- https://modus-web-components.trimble.com/?path=/story/user-inputs-text-input--default
- https://modus-web-components.trimble.com/?path=/story/user-inputs-number-input--default
- https://modus-web-components.trimble.com/?path=/story/user-inputs-date-picker--default
This PR fixes them. Mainly by linking inputs to labels.
> Docs: Fix some accessibility 'incomplete' (warnings) in Canvas demos

- stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
- Added `disabled` button to out of range dates
- Set `aria-current="date"` to one date
Fixes: #2283 
- Locally with Chrome V122 on Windows 10
> Date Picker: Fix Accessibility Issues

- stencil-workspace/storybook/stories/introduction/welcome.stories.mdx
Add link to Netlify from front page
Fixes: #308
- Locally
- https://deploy-preview-2348--moduswebcomponents.netlify.app/ (bottom of page)
> Docs: Add link to Netlify from front page

- stencil-workspace/src/components/modus-switch/modus-switch.spec.tsx
- stencil-workspace/src/components/modus-switch/modus-switch.tsx
Make disabled switches not focusable by making `tabindex` dependent on `disabled`.
References #2270
Added a unit test to verify `tabindex` is -1 when `disabled` attribute is added.
> Switch: Make disabled switches not focusable

- stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Fixes:
- The disabled buttons should not have hover states - let's add `pointer-events: none` CSS
- The title could have `role="header"`
- The calendar dates can have `type="button"` (fixes this Webhint warning: https://webhint.io/docs/user-guide/hints/hint-button-type)
- https://deploy-preview-2344--moduswebcomponents.netlify.app/?path=/story/user-inputs-date-picker--default-with-picker
> Date Picker: Fixes a few usability / accessibility issues

- stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
Fixes an accessibility issue.
- Locally with Edge v122 on Windows 11 Pro
- https://deploy-preview-2307--moduswebcomponents.netlify.app/?path=/story/components-navbar--default&args=showHelp:true;showProfile:false;showSearch:true
> Navbar: Add `aria-label` to Search and Help buttons

- stencil-workspace/src/components/modus-date-input/modus-date-input.scss
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Adds `font-family: $primary-font` to input elements that display some form of text.
References #2353
Added the following to `index.html`: 
```html
<modus-text-input
label="Text Input (Search Icon)"
placeholder="Placeholder"
include-search-icon
required></modus-text-input>
<modus-number-input
label="Number Input Demo 1"
placeholder="Placeholder"
required="true"></modus-number-input>
<modus-date-picker
helper-text="mmm dd, yyyy"
label="Single date"
allowed-chars-regex="[\d\/]"
format="mmm dd, yyyy"
value="2022-12-22"></modus-date-input>
<modus-time-picker
label="Time"
ampm="true"
value="23:39"
placeholder="12:00 AM"
helper-text="hh:mm AM/PM"></modus-time-picker>
```
Also put "Times New Roman" as the first element in `$primary-font` (just as a visual indicator that my changes are, in fact, …
> Input: Add primary-font to input elements designed to display text

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
- stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Add autocapitalize, autocorrect, enterkeyhint, and spellcheck properties to input
References #2347
Added unit tests
> Input: Add `autocapitalize`, `autocorrect`, `enterkeyhint`, and `spellcheck `properties

- stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
- stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.spec.ts
- stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
Remove aria-disabled attribute when not disabled.
Fixes: #2377
Unit and e2e tests
Preview:
https://deploy-preview-2378--moduswebcomponents.netlify.app/?path=/story/components-sentiment-scale--default
> Sentiment Scale: Remove `aria-disabled` attribute when not disabled

- stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
* Delete excessive calls to methods that react to input
* Update tests to better reflect a user journey, replacing existing unit tests with more black-box e2e tests.
References #2392
E2E tests, manually using the following code in `index.html`:
```
<modus-dropdown toggle-element-id="toggleElement">
<modus-button id="toggleElement" slot="dropdownToggle" show-caret="true">Dropdown</modus-button>
<modus-list slot="dropdownList">
<modus-list-item size="condensed" borderless>Item 1</modus-list-item>
<modus-list-item size="condensed" borderless>Item 2</modus-list-item>
<modus-list-item size="condensed" borderless>Item 3</modus-list-item>
</modus-list>
</modus-dropdown>
<modus-text-input></modus-text-input>
```
> Dropdown: Fix issue where enter, escape, and space key are not having desired output

- stencil-workspace/src/components/modus-table/modus-table.scss
- stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx
References ##2309
Tested using the following HTML in the body of `index.html`:
```html
<div style="width: 950px">
<modus-table column-resize="true" />
</div>
<script>
document.querySelector('modus-table').columns = [
{
header: 'First Name',
accessorKey: 'firstName',
id: 'first-name',
dataType: 'text',
size: 150,
minSize: 80
},
{
header: 'Last Name',
accessorKey: 'lastName',
id: 'last-name',
dataType: 'text',
size: 150,
minSize: 80
},
{
header: 'Age',
accessorKey: 'age',
id: 'age',
dataType: 'integer'
},
{
header: 'Visits',
accessorKey: 'visits',
id: 'visits',
dataType: 'integer',
maxSize: 80,
minSize: 80,
enableResizing: false,
},
{
header: 'Status',
accessorKey: 'status',
id: 'status',
dataType: 'text',
minSize: 80
},
{
header: 'Profile Progress',
accessorKey: 'progress',
id: 'progress', …
```
> Table: Fix issue with column sort not being visible when resized too small

- stencil-workspace/storybook/stories/components/modus-badge/modus-badge.stories.tsx
Minor docs change: Badges (counter) Canvas demo to use numbers (not text) as intended.
Fixes: #2422
https://deploy-preview-2423--moduswebcomponents.netlify.app/?path=/story/components-badge--counter
> Docs: badges (counter) Canvas demo to use numbers (not text)

- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
- stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.vars.scss
- stencil-workspace/src/global/themes.scss
- Correct horizontal padding (16px - was 8px)
- Correct Chevron Rotation
Fixes: #2405
https://deploy-preview-2407--moduswebcomponents.netlify.app/?path=/story/components-accordion--default
> Accordion: Style Fixes

- stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
- Update docs with controls
`aria-label`
`disabled`
`name`
`size`
of radio button
References #2435
> Radio Group: Update docs

- stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
- Added for to the label representing the id added to the input from `props.id`
Fixes: #2433
https://deploy-preview-2434--moduswebcomponents.netlify.app/?path=/story/user-inputs-radio-group--medium
> Radio Group: Label mismatch with radio button

- stencil-workspace/src/components/modus-button-group/modus-button-group.e2e.ts
- stencil-workspace/src/components/modus-button-group/modus-button-group.spec.ts
- stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
- stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
Fix accessibility issue if a user adds an `aria-label` since no role was defined.
Fixes this issue:
Local (storybook)
> Button-Group: Add `role="group"`

- stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
- stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
Fix disabled behavior on dropdown element.  Adds `disabled` to toggle element and prevents actions when disabled.
References #2419
Manual using existing Storybook implementation, e2e tests
https://deploy-preview-2456--moduswebcomponents.netlify.app/?path=/story/components-dropdown--default&args=disabled:true
> Dropdown: Fix disabled behavior on dropdown element

- stencil-workspace/src/components/modus-toast/modus-toast.scss
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
- Smaller icon (from 24px to 18px) - now same size as Alert close/dismiss button
- Adds `type="button"` (Fixes this issue: https://webhint.io/docs/user-guide/hints/hint-button-type/)
- Use actual Modus Close icon.
https://deploy-preview-2472--moduswebcomponents.netlify.app/?path=/story/components-toast--default&args=dismissible:true
> Toast: Dismiss Button Style Improvement

- stencil-workspace/src/components/modus-tabs/modus-tabs.e2e.ts
- stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
Fix issue where selecting a tab in a set with no active tab errors out.
References #2197
Added E2E test, manually tested using provided HTML (thank you, reporter)
> Tabs: Fix issue where selecting a tab in a set with no active tab errors out

- stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
Behavior was because of how `modus-tooltip` is implemented (i.e. as a `div`).  Using `inline-block` prevents this behavior.
References  #2438
Manually verify in both Chrome and Firefox
> Tooltip: fix issue with tooltip creating a new line when multiple buttons are in a row

- stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx
- stencil-workspace/src/components/modus-file-dropzone/readme.md
- stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone.stories.tsx
- Added accept property to accept certain file types
References 
Fixes #2003
> File Dropzone: Add accept property

- stencil-workspace/src/components/modus-table/modus-table.core.tsx
- stencil-workspace/src/components/modus-table/modus-table.tsx
- Fixed the manual pagination - `currentpageSize` prop not working on initial load
- Page view select will be empty on user defined page size. 
References 
Fix #2395
> Table: Manual Pagination `currentPagesize` not working on initial load fix

- stencil-workspace/src/components/modus-date-input/modus-date-input.scss
- stencil-workspace/src/components/modus-number-input/modus-number-input.scss
- stencil-workspace/src/components/modus-select/modus-select.scss
- stencil-workspace/src/components/modus-text-input/modus-text-input.scss
- stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
- Updates labels to `font-weight: 700`
- Change default border to be darker for better contrast
- Change focus, error and invalid states to have a visual 2px border all round
References #2281
Locally with Edge v125 on Windows 11 Pro
> Inputs: Revised Form Control Styles (text, number, datepicker and select)

- stencil-workspace/tsconfig.json
Set: `forceConsistentCasingInFileNames` rule to true (tsconfig)
This is recommended by Typescript:
https://www.typescriptlang.org/tsconfig/#forceConsistentCasingInFileNames
I've had this option set locally for several months without any problems.
I discovered this by using WebHint VS Code extension which also recommend using it. https://webhint.io/docs/user-guide/hints/hint-typescript-config/consistent-casing/
I've used this setting locally for a few months with no issues building or running lints/tests.
> Set: `forceConsistentCasingInFileNames` rule to true (tsconfig)

- stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss
Wrap the Navbar's link item text so that it doesn't overflow the width of the menu
References #2085
Tested manually
> Navbar: Wrap link item text

- stencil-workspace/src/components/modus-navbar/main-menu/modus-navbar-main-menu.scss
This PR removes the border rendered by the `custom-navbar-menu` mixin (used by all navbar menus). The border is overridden using ` border: unset` within the `.main-menu` class level styling.
When testing this from the `index.html` file I noticed a margin and padding being applied that caused abnormal rendering issues. I added inline styling to the `body` element to set these values to 0.
I ran the following commands which caused several other minor updates.
`npm run lint`
`npm run prettier`
Fixes #2572
[Issue 2572](https://github.com/trimble-oss/modus-web-components/issues/2572)
Manual testing, no additional testing required for this small of a styling change.
> Navbar: Remove modus navbar main menu border

- stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
Tooltips do not currently wrap lines which can result in very wide tooltips that don't always fit in their container.
We should set `max-width: 250px` in CSS to allow for line-wrap.
Before:
https://modus-web-components.trimble.com/?path=/story/components-tooltip--default&args=text:Tooltip+text+can+be+very+annoying+if+its+too+long+and+not+wrapped
After:
https://deploy-preview-2597--moduswebcomponents.netlify.app/?path=/story/components-tooltip--default&args=text:Tooltip+text+can+be+very+annoying+if+its+too+long+and+not+wrapped
> Tooltip: Set max-width to 250px

- stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.scss
- stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.spec.tsx
- stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.tsx
- stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.vars.scss
- stencil-workspace/storybook/stories/components/modus-textarea-input/modus-textarea-input-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-textarea-input/modus-textarea-input.stories.tsx
- Allows the textarea to be vertically resized
- Adds visible 2px border on focus and valid/invalid states
- Removes the clearable example (seemed unnecessary and looked bad)
- Removed hard-coded height of the inputs
Locally with Edge v125
> Textarea: Input Style Fixes

- stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.scss
- Add readonly state CSS
- Remove unused icons CSS
Preview:
https://deploy-preview-2631--moduswebcomponents.netlify.app/?path=/story/user-inputs-textarea-input--default&args=readOnly:true
> Textarea: readonly state CSS fix

- stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
- Updated the storybook examples by addressing the chips model as multiple selection and adding 17 additional options to chose from overall 20
References 
Fixes #2564 
Its tested in the story book docs and canvas tab with new examples and chips addressed as multiple
> AutoComplete: Cleanup StoryBook examples

- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
- Added profileMenuSignOutClick to action tab which triggers on clicking the signout button inside the profile menu button
References 
Fixes #2635
> Navbar: Add handling of event "profileMenuSignOutClick"

- stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
- stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
- Add Notifications `aria-label` to icon-only button
- Adds false to `aria-disabled` (otherwise it is invalid)
https://deploy-preview-2653--moduswebcomponents.netlify.app/?path=/story/components-button--icon-only
This fixes the Violation (red) and improves the Incomplete warning from a Critical to Serious.
> Docs: Fix accessibilty issues on Buttons Canvas Demo

- stencil-workspace/src/interfaces.d.ts
Export missing types to resolve compilation errors in Angular builds
References #2658 
Locally using the following steps
- Make changes in stencil workspace
- Run `npm run build`
- Run `yalc publish`
- At root level package.json, add `yalc add @trimble-oss/modus-web-components` after each `npm i` in build-angular script then run `npm run build-angular`
> Fix Angular build compilation error

- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
I've changed the cell value validation to only `null` and `undefined` so as not to stop the number 0 from being shown in the table.
References #2647
> Table: Number 0 is visible in the table cells

- stencil-workspace/src/components/modus-toolbar/modus-toolbar.spec.ts
- stencil-workspace/src/components/modus-toolbar/modus-toolbar.tsx
- stencil-workspace/storybook/stories/components/modus-toolbar/modus-toolbar-storybook-docs.mdx
- Added aria labels for toolbar buttons 
- Updated the storybook documentation
References 
Fixes #2619
> Toolbar: Icon only buttons do not have aria-labels

- package-lock.json
- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-navbar/dropdown/modus-navbar-dropdown.tsx
- stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts
- stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
This PR adds a way for the consumer to manually set the Navbar `selectedDropdownItem`. This allows the web component to track changes and emit events. But also allows the user to set it back to a previous value (or whatever they want).
This is a breaking change as it changes the interfaces for the Modus Navbar props.
References #2682
Manually tested and in Storybook.
> Navbar: dropdown allows manual selection

- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
This is a CSS-only fix to improve the disabled state by making border transparent, disabling text select and pointer-events.
https://deploy-preview-2690--moduswebcomponents.netlify.app/?path=/story/user-inputs-autocomplete--default&args=disabled:true
> Autocomplete: Improve disabled state CSS

- stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
- stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group.stories.tsx
- Added selected property to modus button for default selection in single selection type
References 
Fixes #2642 
https://deploy-preview-2678--moduswebcomponents.netlify.app/?path=/docs/components-button-group--single-selection#single-selection
> Button Group: Add default selected property

- stencil-workspace/src/components/modus-table/models/modus-table.models.ts
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/readme.md
I added the placeholder option in the `ModusTableCellSelectEditorArgs` type to send a custom placeholder alongside the options and the display option for the select type cells.
References #2656
> Table: Exposed the placeholder for the select type cells

- stencil-workspace/src/components/modus-toast/modus-toast.scss
- stencil-workspace/src/components/modus-toast/modus-toast.spec.ts
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
- stencil-workspace/src/components/modus-toast/modus-toast.vars.scss
- stencil-workspace/src/global/themes.scss
- stencil-workspace/src/icons/svgs/icon-info.tsx
- stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
- Updates Toasts to match styleguide: https://modus.trimble.com/components/web/toasts/styles/
- Sets width to: 370px
https://deploy-preview-2708--moduswebcomponents.netlify.app/?path=/docs/components-toast--primary
> Toasts: Updated to Match Figma

- stencil-workspace/src/components/modus-button-group/readme.md
- stencil-workspace/src/components/modus-button/modus-button.models.ts
- stencil-workspace/src/components/modus-button/modus-button.scss
- stencil-workspace/src/components/modus-button/modus-button.tsx
- stencil-workspace/src/components/modus-button/modus-button.vars.scss
- stencil-workspace/src/components/modus-button/readme.md
- stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
- Updated css to add a new color property `special`
- Updated docs
References 
Fixes #2518
> Button: Added Special Button and Updated Button documentation sections

- .github/workflows/super-linter.yml
The super linter PR check is failing for all the new PRs since 2024-07-31. Coincidently a new version of super linter 6.8.0 is released on the same day which seems to cause this issue so I'm using the previous version (6.7.0) of super linter until it is resolved.
References #2769
Created a draft PR and the super linter PR check is passed.
> Use previous version of super linter 6.7.0

- stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss
Fixes: #2355 
In Dev Tools you can set `Rendering > Prefers-Reduced-Animation: Reduce`.
Then expanding and collapsing the menu has no animation.
> Side-Navigation: Don't animate if user prefers reduced animation

- stencil-workspace/src/components/modus-table/modus-table.tsx
Set 'columnOrder' state when new `columns` array provided to modus table. This change support column reordering when new columns were added after table's initial render.
References #2811 
Ran all unit and e2e tests using `npm run test`
Exploratory testing locally in index.html file
> Table: Set state when columns property changed

- stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.spec.tsx
- stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
- stencil-workspace/src/components/modus-date-picker/readme.md
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.scss
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx
- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
- Added a prop called `calendar-placement` to set the position of the calendar 
- Added popper function to change position seamlessly while scrolling but the default position is set to bottom-start
References 
Fixes #2802
> Datepicker: Add position property to control component placement relative to the wrapped item

- stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.scss
- stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel-storybook-docs.mdx
Add a custom css property to allow user of utility panel to specify custom padding.
References #2699 
Tested usage of property in storybook.
> Utility Panel: Add custom css property to configure padding

- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> Autocomplete: Update or reset selection on value change in multiselect mode

- stencil-workspace/src/components/modus-button-group/modus-button-group.constants.ts
- stencil-workspace/src/components/modus-button-group/modus-button-group.e2e.ts
- stencil-workspace/src/components/modus-button-group/modus-button-group.spec.ts
- stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
- stencil-workspace/src/components/modus-number-input/readme.md
> Buttongroup:  Handle selection reset for single and multiple selections

- stencil-workspace/src/components/modus-toast/modus-toast.e2e.ts
- stencil-workspace/src/components/modus-toast/modus-toast.tsx
- stencil-workspace/src/components/modus-toast/readme.md
- stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
- stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
- Add `retainELement ` prop to not stop the toast component from getting removed from the dom
References 
Fixes #2835
> Toast: Add prop to retain element on dismiss

- stencil-workspace/src/components/modus-modal/modus-modal.scss
Adds large box-shadow to modal.
```css
box-shadow: 0 0 8px rgba(37, 42, 46, 0.3);
```
1. https://deploy-preview-2926--moduswebcomponents.netlify.app/?path=/story/components-modal--default
2. Open Modal and inspect the modal
> Modal: Box-Shadow CSS

- stencil-workspace/src/global/modus-variables.scss
Remove Google Fonts from Modus Variables CSS
Fixes: #2955
Font still loads from Google Fonts CDN:
https://deploy-preview-2956--moduswebcomponents.netlify.app/?path=/story/components-file-dropzone--default
You just need to include this in your HTML:
```html
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=fallback">
```
> Remove Google Fonts from Modus Variables CSS

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-list-item/modus-list-item.scss
- stencil-workspace/src/components/modus-navbar/modus-navbar.scss
- stencil-workspace/src/components/modus-table/modus-table.scss
Follow on PR from: #2601
Improves Modus Lists, Navbars and Tables using Windows Forced Colors High Contrast themes
Tested with Edge and Chrome on Windows 11 Pro by using the forced-colors: active option in Dev Tools - both light and dark mode.
> Improve Windows Forced-Colors High Contrast Theme Support

- stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
Fixes the alerts background color for web components when the CSS is NOT used. This fix isn't testable via Storybook because the CSS is loaded.
Fixes: #2913 
Locally.
> Alerts: Fix Warning / Error BG color CSS

- stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss
Fixes the text being selected when expanding.
https://deploy-preview-2973--moduswebcomponents.netlify.app/?path=/story/components-content-tree--multi-selection
> Content Tree: Fix text being selected when expanding a section

- stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.spec.ts
- stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.tsx
References
- push content feature not working in the initial stage  
Fixes #3061
> Utility Panel: Content is not pushed in the default expanded state

- stencil-workspace/src/components.d.ts
- stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
- stencil-workspace/src/components/modus-autocomplete/readme.md
- stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx
- stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
References 
- Add focus method to auto-complete
- Add Focus to the autocomplete in Table when edit mode
Fixes #3044
> Table: Add Focus Handling for Autocomplete Input in Table Cells

- stencil-workspace/src/components/modus-chip/modus-chip.e2e.ts
- stencil-workspace/src/components/modus-chip/modus-chip.tsx
References 
This PR fixes 
1. prevents event emit / focus  on keyboard navigation
2. prevents duplicate event emission on pressing enter
3. adding event emission for space key
Fixes #3105 
https://deploy-preview-3106--moduswebcomponents.netlify.app/
> Chip: Prevent event emit on keydown in disabled state

- stencil-workspace/stencil.config.ts
this is required for React v19... and MWC v2 has it
https://github.com/trimble-oss/modus-wc-2.0/blob/main/stencil.config.ts#L34
GitHub Copilot says this:
> The externalRuntime: false setting in your StencilJS configuration is important and should be kept.
> 
> This setting controls how the Stencil runtime is handled in your custom elements output. When set to false (as it currently is), it bundles the necessary runtime code with each component, making them more self-contained and independently usable. This means:
> 
> Each custom element will work on its own without requiring separate loading of the Stencil runtime.
> Components can be used directly in any web project without additional dependencies.
> It provides better compatibility across different environments.
> If you were to remove …
> Stencil Config Update: Add `externalRuntime: false`

- stencil-workspace/stylelint.config.mjs
Potential fix for [https://github.com/trimble-oss/modus-web-components/security/code-scanning/31](https://github.com/trimble-oss/modus-web-components/security/code-scanning/31)
To fix the issue, we need to remove the duplicate property `'declaration-property-value-keyword-no-deprecated'` from the `rules` object. Since both instances assign the same value (`null`), removing either one will not affect the functionality of the code. The best approach is to remove the second occurrence (line 10) to preserve the original order of properties in the object.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 31: Duplicate property

- stencil-workspace/src/components/modus-slider/modus-slider.scss
- stencil-workspace/src/components/modus-slider/modus-slider.spec.ts
- stencil-workspace/src/components/modus-slider/modus-slider.tsx
- stencil-workspace/src/components/modus-slider/readme.md
There is no difference in the visibility of selected and non selected part of the slider as 
the entire part is shown in blue color.
https://deploy-preview-3026--moduswebcomponents.netlify.app/?path=/story/components-slider--default
References #2717
> Slider: fix modus slider selection

- .github/dependabot.yml
- .npmrc
- angular-workspace/adding-angular-integrations.md
- angular-workspace/ng16/.npmrc
- angular-workspace/ng16/projects/trimble-oss/modus-angular-components/.npmrc
- angular-workspace/ng17/.npmrc
- angular-workspace/ng17/projects/trimble-oss/modus-angular-components/.npmrc
- angular-workspace/ng18/package-lock.json
- angular-workspace/ng18/projects/trimble-oss/modus-angular-components/.npmrc
- angular-workspace/ng19/.npmrc
- angular-workspace/ng19/projects/trimble-oss/modus-angular-components/.npmrc
- angular-workspace/ng20/.npmrc
- angular-workspace/ng20/projects/trimble-oss/modus-angular-components/.npmrc
- angular-workspace/test-ng15/.npmrc
- react-workspace/react-17/.npmrc
- react-workspace/react-18/.npmrc
- react-workspace/react-18/package-lock.json
- react-workspace/react-19/.npmrc
- react-workspace/test-react-v17/package-lock.json
- react-workspace/test-react-v18/.npmrc
- react-workspace/test-react-v18/package-lock.json
- react-workspace/test-react-v19/.npmrc
- react-workspace/test-react-v19/package-lock.json
- react-workspace/test-web-components/.npmrc
- react-workspace/test-web-components/package-lock.json
- stencil-workspace/package-lock.json
- stencil-workspace/package.json
- stencil-workspace/storybook/.npmrc
- stencil-workspace/storybook/package-lock.json
This pull request makes several dependency and configuration updates to improve consistency, reduce maintenance overhead, and keep packages up to date. The most notable changes are the switch to monthly updates for Dependabot, removal of `lockfile-version` from multiple `.npmrc` files, and package upgrades for Angular and React workspaces.
**Dependency and configuration management:**
* Changed Dependabot update schedule from weekly to monthly and reduced the open pull request limit from 2 to 1 for `npm` and `github-actions` ecosystems in `.github/dependabot.yml`. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L6-R7) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L18-R23)
* Removed the `lockfile-version` …
> npm audit fixes
